### ISSUE TITLE
Cannot run or build, reforge v1.32.10

### ISSUE THREAD

**Issue by KingOfDuck** [wurstscript/WurstScript#1045]
When I was trying building map, shows internal error,
Then I use wurstscript.exe to build, and then error shows

java.lang.RuntimeException: map mpq is null
        at de.peeeq.wurstio.WurstCompilerJassImpl.processMap(WurstCompilerJassImpl.java:648)
        at de.peeeq.wurstio.WurstCompilerJassImpl.parseFiles(WurstCompilerJassImpl.java:242)
        at de.peeeq.wurstio.CompilationProcess.doCompilation(CompilationProcess.java:59)
        at de.peeeq.wurstio.CompilationProcess.doCompilation(CompilationProcess.java:45)
        at de.peeeq.wurstio.Main.main(Main.java:156)

and when using grill build, it stucked, should I rollback my war3 version to classic?

**Comment by Frotty** [comment]
Please use the bug report issue template and provide the mentioned logs, it's there for a reason.
