### ISSUE TITLE
SEVERE ERROR - Model has errors

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstScript#548]
Symptoms: when running vscode' runmap, "copying map" appears, and then compiler dies without further user experience

I have this in logs:

```
2017-08-15 23:50:25 SEVERE Error
java.lang.RuntimeException: Model has errors
	at de.peeeq.wurstio.languageserver.requests.RunMap.compileScript(RunMap.java:229)
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:97)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:27)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$34(LanguageWorker.java:151)
	at de.peeeq.wurstio.languageserver.LanguageWorker$$Lambda$37/104433951.run(Unknown Source)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:126)
	at java.lang.Thread.run(Thread.java:745)
```

And I think this might be relevant? (vscode draws a red squiggly at the end of this line):

https://bitbucket.org/Cokemonkey11/windwalked/src/e0b87f4a16b881dee74f74abac6433e46df57884/wurst/event-response/Creeps.wurst?at=master&fileviewer=file-view-default#Creeps.wurst-91

**Comment by peq** [comment]
You cannot run a map if the code has errors. It should give a better error message now and you can now indent the `end` keyword as you like.
