### ISSUE TITLE
NPE in transformTypeParams

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#558]
````
java.lang.NullPointerException
    at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformTypeParams(AntlrWurstParseTreeTransformer.java:1203)
    at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformFuncSig(AntlrWurstParseTreeTransformer.java:1118)
    at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformFuncDef(AntlrWurstParseTreeTransformer.java:501)
    at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformClassSlot(AntlrWurstParseTreeTransformer.java:404)
    at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformClassSlots(AntlrWurstParseTreeTransformer.java:363)
    at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformClassDef(AntlrWurstParseTreeTransformer.java:481)
    at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformEntity(AntlrWurstParseTreeTransformer.java:259)
    at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformPackage(AntlrWurstParseTreeTransformer.java:237)
    at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transform(AntlrWurstParseTreeTransformer.java:43)
    at de.peeeq.wurstscript.WurstParser.parseWithAntlr(WurstParser.java:107)
    at de.peeeq.wurstscript.WurstParser.parse(WurstParser.java:38)
    at de.peeeq.wurstio.WurstCompilerJassImpl.parse(WurstCompilerJassImpl.java:591)
    at de.peeeq.wurstio.languageserver.ModelManagerImpl.replaceCompilationUnit(ModelManagerImpl.java:486)
    at de.peeeq.wurstio.languageserver.ModelManagerImpl.replaceCompilationUnitContent(ModelManagerImpl.java:459)
    at de.peeeq.wurstio.languageserver.requests.CodeActionRequest.execute(CodeActionRequest.java:49)
    at de.peeeq.wurstio.languageserver.requests.CodeActionRequest.execute(CodeActionRequest.java:25)
    at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:30)
    at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$36(LanguageWorker.java:152)
    at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:127)
    at java.lang.Thread.run(Unknown Source)
````

**Comment by peq** [comment]
Fixed, but I don't have an example to add a unit test. Do you have one @Frotty ? Maybe this only happens if there are parse errors before.
