### ISSUE TITLE
NPE in $/setTraceNotification ?

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstScript#559]
```
initializing 
2017-10-09 21:42:21 INFO   Unsupported notification method: $/setTraceNotification
java.lang.NullPointerException
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassStatements(AntlrWurstParseTreeTransformer.java:156)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassFuncDef(AntlrWurstParseTreeTransformer.java:136)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassToplevelDecl(AntlrWurstParseTreeTransformer.java:61)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transform(AntlrWurstParseTreeTransformer.java:40)
	at de.peeeq.wurstscript.WurstParser.parseWithAntlr(WurstParser.java:107)
	at de.peeeq.wurstscript.WurstParser.parse(WurstParser.java:38)
	at de.peeeq.wurstio.WurstCompilerJassImpl.parse(WurstCompilerJassImpl.java:591)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.replaceCompilationUnit(ModelManagerImpl.java:486)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.replaceCompilationUnitContent(ModelManagerImpl.java:459)
	at de.peeeq.wurstio.languageserver.requests.GetCompletions.execute(GetCompletions.java:70)
	at de.peeeq.wurstio.languageserver.requests.GetCompletions.execute(GetCompletions.java:31)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:30)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$36(LanguageWorker.java:152)
	at de.peeeq.wurstio.languageserver.LanguageWorker$$Lambda$39/562782108.run(Unknown Source)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:127)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassStatements(AntlrWurstParseTreeTransformer.java:156)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassFuncDef(AntlrWurstParseTreeTransformer.java:136)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassToplevelDecl(AntlrWurstParseTreeTransformer.java:61)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transform(AntlrWurstParseTreeTransformer.java:40)
	at de.peeeq.wurstscript.WurstParser.parseWithAntlr(WurstParser.java:107)
	at de.peeeq.wurstscript.WurstParser.parse(WurstParser.java:38)
	at de.peeeq.wurstio.WurstCompilerJassImpl.parse(WurstCompilerJassImpl.java:591)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.replaceCompilationUnit(ModelManagerImpl.java:486)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.replaceCompilationUnitContent(ModelManagerImpl.java:459)
	at de.peeeq.wurstio.languageserver.requests.CodeActionRequest.execute(CodeActionRequest.java:49)
	at de.peeeq.wurstio.languageserver.requests.CodeActionRequest.execute(CodeActionRequest.java:25)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:30)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$36(LanguageWorker.java:152)
	at de.peeeq.wurstio.languageserver.LanguageWorker$$Lambda$39/562782108.run(Unknown Source)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:127)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassStatements(AntlrWurstParseTreeTransformer.java:156)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassFuncDef(AntlrWurstParseTreeTransformer.java:136)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassToplevelDecl(AntlrWurstParseTreeTransformer.java:61)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transform(AntlrWurstParseTreeTransformer.java:40)
	at de.peeeq.wurstscript.WurstParser.parseWithAntlr(WurstParser.java:107)
	at de.peeeq.wurstscript.WurstParser.parse(WurstParser.java:38)
	at de.peeeq.wurstio.WurstCompilerJassImpl.parse(WurstCompilerJassImpl.java:591)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.replaceCompilationUnit(ModelManagerImpl.java:486)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.syncCompilationUnitContent(ModelManagerImpl.java:452)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$37(LanguageWorker.java:168)
	at de.peeeq.wurstio.languageserver.LanguageWorker$$Lambda$44/1243869387.run(Unknown Source)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:127)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassStatements(AntlrWurstParseTreeTransformer.java:156)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassFuncDef(AntlrWurstParseTreeTransformer.java:136)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassToplevelDecl(AntlrWurstParseTreeTransformer.java:61)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transform(AntlrWurstParseTreeTransformer.java:40)
	at de.peeeq.wurstscript.WurstParser.parseWithAntlr(WurstParser.java:107)
	at de.peeeq.wurstscript.WurstParser.parse(WurstParser.java:38)
	at de.peeeq.wurstio.WurstCompilerJassImpl.parse(WurstCompilerJassImpl.java:591)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.replaceCompilationUnit(ModelManagerImpl.java:486)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.syncCompilationUnitContent(ModelManagerImpl.java:452)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$37(LanguageWorker.java:168)
	at de.peeeq.wurstio.languageserver.LanguageWorker$$Lambda$44/1243869387.run(Unknown Source)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:127)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassStatements(AntlrWurstParseTreeTransformer.java:156)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassFuncDef(AntlrWurstParseTreeTransformer.java:136)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassToplevelDecl(AntlrWurstParseTreeTransformer.java:61)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transform(AntlrWurstParseTreeTransformer.java:40)
	at de.peeeq.wurstscript.WurstParser.parseWithAntlr(WurstParser.java:107)
	at de.peeeq.wurstscript.WurstParser.parse(WurstParser.java:38)
	at de.peeeq.wurstio.WurstCompilerJassImpl.parse(WurstCompilerJassImpl.java:591)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.replaceCompilationUnit(ModelManagerImpl.java:486)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.syncCompilationUnitContent(ModelManagerImpl.java:452)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$37(LanguageWorker.java:168)
	at de.peeeq.wurstio.languageserver.LanguageWorker$$Lambda$44/1243869387.run(Unknown Source)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:127)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassStatements(AntlrWurstParseTreeTransformer.java:156)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassFuncDef(AntlrWurstParseTreeTransformer.java:136)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassToplevelDecl(AntlrWurstParseTreeTransformer.java:61)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transform(AntlrWurstParseTreeTransformer.java:40)
	at de.peeeq.wurstscript.WurstParser.parseWithAntlr(WurstParser.java:107)
	at de.peeeq.wurstscript.WurstParser.parse(WurstParser.java:38)
	at de.peeeq.wurstio.WurstCompilerJassImpl.parse(WurstCompilerJassImpl.java:591)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.replaceCompilationUnit(ModelManagerImpl.java:486)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.syncCompilationUnitContent(ModelManagerImpl.java:452)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$37(LanguageWorker.java:168)
	at de.peeeq.wurstio.languageserver.LanguageWorker$$Lambda$44/1243869387.run(Unknown Source)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:127)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassStatements(AntlrWurstParseTreeTransformer.java:156)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassFuncDef(AntlrWurstParseTreeTransformer.java:136)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassToplevelDecl(AntlrWurstParseTreeTransformer.java:61)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transform(AntlrWurstParseTreeTransformer.java:40)
	at de.peeeq.wurstscript.WurstParser.parseWithAntlr(WurstParser.java:107)
	at de.peeeq.wurstscript.WurstParser.parse(WurstParser.java:38)
	at de.peeeq.wurstio.WurstCompilerJassImpl.parse(WurstCompilerJassImpl.java:591)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.replaceCompilationUnit(ModelManagerImpl.java:486)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.syncCompilationUnitContent(ModelManagerImpl.java:452)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$37(LanguageWorker.java:168)
	at de.peeeq.wurstio.languageserver.LanguageWorker$$Lambda$44/1243869387.run(Unknown Source)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:127)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassStatements(AntlrWurstParseTreeTransformer.java:156)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassFuncDef(AntlrWurstParseTreeTransformer.java:136)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassToplevelDecl(AntlrWurstParseTreeTransformer.java:61)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transform(AntlrWurstParseTreeTransformer.java:40)
	at de.peeeq.wurstscript.WurstParser.parseWithAntlr(WurstParser.java:107)
	at de.peeeq.wurstscript.WurstParser.parse(WurstParser.java:38)
	at de.peeeq.wurstio.WurstCompilerJassImpl.parse(WurstCompilerJassImpl.java:591)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.replaceCompilationUnit(ModelManagerImpl.java:486)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.replaceCompilationUnitContent(ModelManagerImpl.java:459)
	at de.peeeq.wurstio.languageserver.requests.CodeActionRequest.execute(CodeActionRequest.java:49)
	at de.peeeq.wurstio.languageserver.requests.CodeActionRequest.execute(CodeActionRequest.java:25)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:30)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$36(LanguageWorker.java:152)
	at de.peeeq.wurstio.languageserver.LanguageWorker$$Lambda$39/562782108.run(Unknown Source)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:127)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassStatements(AntlrWurstParseTreeTransformer.java:156)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassFuncDef(AntlrWurstParseTreeTransformer.java:136)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transformJassToplevelDecl(AntlrWurstParseTreeTransformer.java:61)
	at de.peeeq.wurstscript.parser.antlr.AntlrWurstParseTreeTransformer.transform(AntlrWurstParseTreeTransformer.java:40)
	at de.peeeq.wurstscript.WurstParser.parseWithAntlr(WurstParser.java:107)
	at de.peeeq.wurstscript.WurstParser.parse(WurstParser.java:38)
	at de.peeeq.wurstio.WurstCompilerJassImpl.parse(WurstCompilerJassImpl.java:591)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.replaceCompilationUnit(ModelManagerImpl.java:486)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.syncCompilationUnitContent(ModelManagerImpl.java:452)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$37(LanguageWorker.java:168)
	at de.peeeq.wurstio.languageserver.LanguageWorker$$Lambda$44/1243869387.run(Unknown Source)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:127)
	at java.lang.Thread.run(Thread.java:745)

```

I don't otherwise see anything bad happening. This appears in console while editing a wurst file.

There was a short 2-3 second pause of lag before this appeared.

**Comment by peq** [comment]
`Unsupported notification method: $/setTraceNotification` is an unrelated warning, which you can ignore. It's just because the language server protocol library we are using does not understand this message I think.

This is a bug in the `AntlrWurstParseTreeTransformer` transformer. Probably you had some syntax error and so some parts of the AST were null.

I have to make this more robust since it seems that Antlr4 can return a syntax tree where everything can be null.

**Comment by peq** [comment]
fixed in https://github.com/wurstscript/WurstScript/commit/09660bcbcb49d8e1fbd3f8c8698aa409d32de06e
