### ISSUE TITLE
[Error] Request textDocument/hover failed.

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#561]
````
2017-10-12 21:25:19 SEVERE Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:53)
    at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:105)
    at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:203)
    at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:139)
    at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
    at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
    at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51)
    ... 11 more
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 3: git:/c%3A/Users/Frotty/Documents/GitHub/Frentity/wurst/entity/Event.wurst?%7B%22path%22%3A%22c%3A%5C%5CUsers%5C%5CFrotty%5C%5CDocuments%5C%5CGitHub%5C%5CFrentity%5C%5Cwurst%5C%5Centity%5C%5CEvent.wurst%22%2C%22ref%22%3A%22~%22%7D
    at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
    at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
    at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
    at sun.nio.fs.WindowsPath.parse(Unknown Source)
    at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
    at java.nio.file.Paths.get(Unknown Source)
    at de.peeeq.wurstio.languageserver.WFile.create(WFile.java:40)
    at de.peeeq.wurstio.languageserver.requests.HoverInfo.<init>(HoverInfo.java:32)
    at de.peeeq.wurstio.languageserver.WurstTextDocumentService.hover(WurstTextDocumentService.java:38)
    ... 15 more
 
[Error - 21:25:19] Request textDocument/hover failed.
  Message: Internal error, please look at the server's logs.
  Code: -32603
2017-10-12 21:25:51 WARNING Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "textDocument/didChange",
  "params": {
    "textDocument": {
      "version": 2,
      "uri": "git:/c%3A/Users/Frotty/Documents/GitHub/Frentity/wurst/entity/Event.wurst?%7B%22path%22%3A%22c%3A%5C%5CUsers%5C%5CFrotty%5C%5CDocuments%5C%5CGitHub%5C%5CFrentity%5C%5Cwurst%5C%5Centity%5C%5CEvent.wurst%22%2C%22ref%22%3A%22~%22%7D"
    },
    "contentChanges": [
      {
        "text": "package Event\nimport public EventHelper\nimport RegisterEvents\nimport OnUnitEnterLeave\nimport ClosureTimers\nimport AbilityObjEditing\nimport initlater DebugInfo\n//Listens to all PLAYER_UNIT_EVENTS plus EVENT_PLAYER_LEAVE and EVENT_UNIT_DAMAGED\n\npublic constant EVENT_PLAYER_CHAT_FIX \u003d ConvertPlayerEvent(96)\n\npublic abstract class EventListener\n\tstatic EventListener array generalListenersFirsts\n\tstatic EventListener array unitListenersFirsts\n\n\tint eventId \u003d 0\n\tEventListener next \u003d null\n\n\tabstract function onEvent()\n\t\n\tstatic function add(eventid eventId, EventListener listener)\n\t\tlistener.eventId \u003d eventId.toIntId()\n\t\tif generalListenersFirsts[listener.eventId] !\u003d null\n\t\t\tlistener.next \u003d generalListenersFirsts[listener.eventId]\n\n\t\tgeneralListenersFirsts[listener.eventId] \u003d listener\n\t\t\n\tstatic function add(unit u, eventid eventId, EventListener listener)\n\t\tlet uid \u003d u.getUserData()\n\t\tif uid \u003c\u003d 0\n\t\t\treturn\n\t\tlistener.eventId \u003d eventId.toIntId()\n\t\t// print(\"adding eventlistener to entityid: \" + uid.toString() + \" eventid: \" + listener.eventId.toString())\n\t\tif unitListenersFirsts[uid] !\u003d null\n\t\t\t// print(\"unit alrdy has listeners\")\n\t\t\tlistener.next \u003d unitListenersFirsts[uid]\n\t\tunitListenersFirsts[uid] \u003d listener\n\t\t\t\n\tstatic function generalEventCallback()\n\t\tlet trigUnit \u003d GetTriggerUnit()\n\t\tlet id \u003d GetTriggerEventId().toIntId()\n\t\teventCallbacksPerSecond++\n\t\t// Unit Listeners\n\t\tif trigUnit !\u003d null\n\t\t\tif trigUnit.hasAbility(DONT_FIRE_EVENTS_ID)\n\t\t\t\treturn\n\t\t\telse if unitListenersFirsts[trigUnit.getUserData()] !\u003d null\n\t\t\t\tvar listener \u003d unitListenersFirsts[trigUnit.getUserData()]\n\t\t\t\twhile listener !\u003d null\n\t\t\t\t\tif listener.eventId \u003d\u003d id\n\t\t\t\t\t\t// print(\"Execute Listener\")\n\t\t\t\t\t\tlistener.onEvent()\n\t\t\t\t\tlistener \u003d listener.next\n\t\t// General Listeners\t\t\n\t\tif generalListenersFirsts[id] !\u003d null\n\t\t\tvar listener \u003d generalListenersFirsts[id]\n\t\t\twhile listener !\u003d null\n\t\t\t\tlistener.onEvent()\n\t\t\t\tlistener \u003d listener.next\n\t\t\n\tondestroy\n\t\tnext \u003d null\n\t\ntrigger unitTrig \u003d CreateTrigger()\ntrigger leaveTrig \u003d CreateTrigger()\ntrigger keyTrig \u003d CreateTrigger()\ntrigger chatTrig \u003d CreateTrigger()\n\npublic function eventid.toIntId() returns int\n\tvar id \u003d eventidToIndex[this.getHandleId()]\n\tif id \u003d\u003d 0\n\t\tid \u003d registerEventId(this)\n\treturn id\n\t\t\t\nint array eventidToIndex\nint eventTypeCounter \u003d 0\n\nfunction registerEventId(eventid evnt) returns int\n\tlet eventId \u003d evnt.getHandleId()\n\teventTypeCounter++\n\teventidToIndex[eventId] \u003d eventTypeCounter\n\tif evnt.isPlayerunitEvent()\n\t\tprintLog(Loglevel.DEBUG, \"reg handleid: \" + eventId.toString() + \" -\u003e eventId: \" + eventTypeCounter.toString())\n\t\tregisterPlayerUnitEvent(ConvertPlayerUnitEvent(eventId), function EventListener.generalEventCallback)\n\telse if evnt !\u003d EVENT_UNIT_DAMAGED and evnt !\u003d EVENT_PLAYER_LEAVE and evnt !\u003d EVENT_PLAYER_CHAT_FIX and not evnt.isKeyboardEvent()\n\t\tprintLog(Loglevel.ERROR, \"registering handleid: \" + eventId.toString() + \" non-playerunitevent. Except EVENT_UNIT_DAMAGED and EVENT_PLAYER_LEAVE these are not supported right now.\")\n\treturn eventTypeCounter\n\t\nfunction registerEventsForUnit(unit u)\n\tunitTrig.registerUnitEvent(u, EVENT_UNIT_DAMAGED)\n\npublic function unregisterEventsForUnit(unit u)\n\tunregisterEvents(u.getUserData())\n\npublic function unregisterEvents(int id)\n\tif id \u003e 0 and EventListener.unitListenersFirsts[id] !\u003d null\n\t\tprintLog(Loglevel.TRACE, \"unregister unit has listeners. startid: \" + id.toString())\n\t\tvar listener \u003d EventListener.unitListenersFirsts[id]\n\t\tEventListener.unitListenersFirsts[id] \u003d null\n\t\twhile listener !\u003d null\n\t\t\tlet t \u003d listener\n\t\t\tlistener \u003d listener.next\n\t\t\tdestroy t\n\ninit\n\tdoAfter(0.0, () -\u003e begin\n\t\t// Register Events when unit enters map\n\t\tonEnter(() -\u003e registerEventsForUnit(getEnterLeaveUnit()))\n\t\t// Delete \n\t\tonLeave(() -\u003e unregisterEventsForUnit(getEnterLeaveUnit()))\n\t\t\n\t\t// Register Actions\n\t\tunitTrig.addAction(() -\u003e EventListener.generalEventCallback())\t\n\t\tleaveTrig.addAction(() -\u003e EventListener.generalEventCallback())\n\t\tchatTrig.addAction(() -\u003e EventListener.generalEventCallback())\n\t\tkeyTrig.addAction(() -\u003e EventListener.generalEventCallback())\n\n\t\tfor i \u003d 0 to bj_MAX_PLAYERS-1\n\t\t\tchatTrig.registerPlayerChatEvent(players[i], \"\", false)\n\t\t\tleaveTrig.registerPlayerEvent(players[i], EVENT_PLAYER_LEAVE)\n\t\t\tkeyTrig..registerPlayerEvent(players[i], EVENT_PLAYER_ARROW_DOWN_DOWN)\n\t\t\t..registerPlayerEvent(players[i], EVENT_PLAYER_ARROW_DOWN_UP)\n\t\t\t..registerPlayerEvent(players[i], EVENT_PLAYER_ARROW_UP_DOWN)\n\t\t\t..registerPlayerEvent(players[i], EVENT_PLAYER_ARROW_UP_UP)\n\t\t\t..registerPlayerEvent(players[i], EVENT_PLAYER_ARROW_LEFT_DOWN)\n\t\t\t..registerPlayerEvent(players[i], EVENT_PLAYER_ARROW_LEFT_UP)\n\t\t\t..registerPlayerEvent(players[i], EVENT_PLAYER_ARROW_RIGHT_DOWN)\n\t\t\t..registerPlayerEvent(players[i], EVENT_PLAYER_ARROW_RIGHT_UP)\n\t\t\t..registerPlayerEvent(players[i], EVENT_PLAYER_END_CINEMATIC)\n\tend)\n\npublic constant DONT_FIRE_EVENTS_ID \u003d \u0027dont\u0027\n@compiletime function genObj()\n\tnew AbilityDefinitionDefenseBonusPlus1(DONT_FIRE_EVENTS_ID)\n\t..setDefenseBonus(1, 0)\n\t..setName(\"Dummy Event Ability\")"
      }
    ]
  }
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:53)
    at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:126)
    at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:165)
    at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:136)
    at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
    at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
    at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51)
    ... 11 more
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 3: git:/c%3A/Users/Frotty/Documents/GitHub/Frentity/wurst/entity/Event.wurst?%7B%22path%22%3A%22c%3A%5C%5CUsers%5C%5CFrotty%5C%5CDocuments%5C%5CGitHub%5C%5CFrentity%5C%5Cwurst%5C%5Centity%5C%5CEvent.wurst%22%2C%22ref%22%3A%22~%22%7D
    at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
    at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
    at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
    at sun.nio.fs.WindowsPath.parse(Unknown Source)
    at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
    at java.nio.file.Paths.get(Unknown Source)
    at de.peeeq.wurstio.languageserver.WFile.create(WFile.java:40)
    at de.peeeq.wurstio.languageserver.BufferManager.handleChange(BufferManager.java:61)
    at de.peeeq.wurstio.languageserver.LanguageWorker.handleChange(LanguageWorker.java:229)
    at de.peeeq.wurstio.languageserver.WurstTextDocumentService.didChange(WurstTextDocumentService.java:129)
    ... 15 more
````

**Comment by peq** [comment]
Could be fixed. If not I need more info about how to get URIs like `git:/c%3A/Users/Frotty/Documents/GitHub/Frentity/wurst/entity/Event.wurst?%7B%22path%22%3A%22c%3A%5C%5CUsers%5C%5CFrotty%5C%5CDocuments%5C%5CGitHub%5C%5CFrentity%5C%5Cwurst%5C%5Centity%5C%5CEvent.wurst%22%2C%22ref%22%3A%22~%22%7D`
