### ISSUE TITLE
Returning "vec2" with usage of randomPoint()

### ISSUE THREAD

**Issue by DDLegionTN** [wurstscript/WurstScript#579]
Another issue from me, which took up plenty of my time to narrow down to simplest form of the problem.

```
function A() returns vec2
    return Rect(0, 0, 10, 10).randomPoint()

init
    let v = A()
```

When running above code, it is fine (without optimization "inline" enabled)
If enabled "inline" optimization, then such error will appear :
![image](https://user-images.githubusercontent.com/10547551/32980405-e40de388-cca0-11e7-86bf-86c458ed9666.png)
Here's the log :

32:33  INFO: parsed attributes
32:33  INFO: Building mpq
32:33  INFO: Sorted blocks
32:33  INFO: Added existing files
32:33  INFO: Added new files
32:33  INFO: Added listfile
32:33  INFO: Rebuild complete. Took: 12ms
32:36  INFO: Building mpq
32:36  INFO: Sorted blocks
32:36  INFO: Added existing files
32:36  INFO: Added file war3map.w3u
32:36  INFO: Added file war3map.w3a
32:36  INFO: Added file dummy.mdx
32:36  INFO: Added file war3map.imp
32:36  INFO: Added new files
32:36  INFO: Added listfile
32:36  INFO: Rebuild complete. Took: 23ms
java.lang.Error: contains tuple expr <GetRandomReal({
    this145 = this155;
    >>>  GetRectMinX(this145)}, {
    this212 = this155;
    >>>  GetRectMaxX(this212)}), GetRandomReal({
    this168 = this155;
    >>>  GetRectMinY(this168)}, {
    this932 = this155;
    >>>  GetRectMaxY(this932)})>
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1201)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1217)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1217)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1217)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1217)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1217)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1217)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1187)
	at de.peeeq.wurstscript.translation.imtranslation.EliminateTuples.eliminateTuplesProg(EliminateTuples.java:34)
	at de.peeeq.wurstscript.jassIm.ImProgImpl.eliminateTuples(ImProgImpl.java:158)
	at de.peeeq.wurstio.WurstCompilerJassImpl.transformProgToJass(WurstCompilerJassImpl.java:376)
	at de.peeeq.wurstio.languageserver.requests.RunMap.compileScript(RunMap.java:304)
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:119)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$54(LanguageWorker.java:172)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:29)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:146)
	at java.lang.Thread.run(Unknown Source)
Error in request 'de.peeeq.wurstio.languageserver.requests.RunMap@59cc0189' (see log for details): contains tuple expr <GetRandomReal({
    this145 = this155;
    >>>  GetRectMinX(this145)}, {
    this212 = this155;
    >>>  GetRectMaxX(this212)}), GetRandomReal({
    this168 = this155;
    >>>  GetRectMinY(this168)}, {
    this932 = this155;
    >>>  GetRectMaxY(this932)})>

**Comment by DDLegionTN** [comment]
Thanks for your fast fix, but issue is still persist for me, even above code for now is working, but the code is not working for the following code :

```
package Hello

import ClosureTimers

tuple Tuple1(vec2 v, real r)

function B() returns Tuple1
    return Tuple1(Rect(0, 0, 10, 10).randomPoint(), 10.)

function A()
    doAfter(10, () -> B())
```
Removing "real r" from Tuple1 will make the code works, though.

![image](https://user-images.githubusercontent.com/10547551/32981671-94df2c14-ccb3-11e7-9c9f-9066b770926a.png)

Error log :

14:05  INFO: parsed attributes
14:05  INFO: Building mpq
14:05  INFO: Sorted blocks
14:05  INFO: Added existing files
14:05  INFO: Added new files
14:05  INFO: Added listfile
14:05  INFO: Rebuild complete. Took: 23ms
14:10  INFO: Building mpq
14:10  INFO: Sorted blocks
14:10  INFO: Added existing files
14:10  INFO: Added file war3map.w3u
14:10  INFO: Added file war3map.w3a
14:10  INFO: Added file dummy.mdx
14:10  INFO: Added file war3map.imp
14:10  INFO: Added new files
14:10  INFO: Added listfile
14:10  INFO: Rebuild complete. Took: 23ms
java.lang.Error: contains tuple expr <GetRandomReal({
    this314 = this643;
    >>>  GetRectMinX(this314)}, {
    this888 = this643;
    >>>  GetRectMaxX(this888)}), GetRandomReal({
    this152 = this643;
    >>>  GetRectMinY(this152)}, {
    this192 = this643;
    >>>  GetRectMaxY(this192)})>
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1201)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1217)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1217)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1217)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1217)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1217)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1217)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1217)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1217)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1217)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1217)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1217)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1217)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1217)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1217)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1217)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.assertProperties(ImTranslator.java:1187)
	at de.peeeq.wurstscript.translation.imtranslation.EliminateTuples.eliminateTuplesProg(EliminateTuples.java:34)
	at de.peeeq.wurstscript.jassIm.ImProgImpl.eliminateTuples(ImProgImpl.java:158)
	at de.peeeq.wurstio.WurstCompilerJassImpl.transformProgToJass(WurstCompilerJassImpl.java:376)
	at de.peeeq.wurstio.languageserver.requests.RunMap.compileScript(RunMap.java:308)
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:123)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$54(LanguageWorker.java:172)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:29)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:146)
	at java.lang.Thread.run(Unknown Source)
Error in request 'de.peeeq.wurstio.languageserver.requests.RunMap@5dd49a9c' (see log for details): contains tuple expr <GetRandomReal({
    this314 = this643;
    >>>  GetRectMinX(this314)}, {
    this888 = this643;
    >>>  GetRectMaxX(this888)}), GetRandomReal({
    this152 = this643;
    >>>  GetRectMinY(this152)}, {
    this192 = this643;
    >>>  GetRectMaxY(this192)})>

**Comment by peq** [comment]
Seems like the inliner destroyed an assumption needed by the tuple elimination code. I hope the latest commit fixes these kind of problems.
