### ISSUE TITLE
Cannot translate array type <type> array array

### ISSUE THREAD

**Issue by DDLegionTN** [wurstscript/WurstScript#581]
I'm unsure what to name with the title, anywhere this code

```
let a = [1,2]

let b = [a]
```
Will have error, error log :

initializing 
00:00  INFO: parsed attributes
00:00  INFO: Building mpq
00:00  INFO: Sorted blocks
00:00  INFO: Added existing files
00:00  INFO: Added new files
00:00  INFO: Added listfile
00:00  INFO: Rebuild complete. Took: 29ms
java.lang.Error: cannot translate array type integer array(dimensions = 1) array(dimensions = 1)  array integer
	at de.peeeq.wurstscript.types.WurstTypeArray.imTranslateType(WurstTypeArray.java:89)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.getVarFor(ImTranslator.java:743)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translateVar(TLDTranslation.java:20)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:27)
	at de.peeeq.wurstscript.ast.GlobalVarDefImpl.imTranslateEntity(GlobalVarDefImpl.java:369)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:59)
	at de.peeeq.wurstscript.ast.WPackageImpl.imTranslateTLD(WPackageImpl.java:402)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.translateCompilationUnit(ImTranslator.java:303)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.translateProg(ImTranslator.java:118)
	at de.peeeq.wurstio.WurstCompilerJassImpl.translateProgToIm(WurstCompilerJassImpl.java:458)
	at de.peeeq.wurstio.languageserver.requests.RunMap.compileScript(RunMap.java:283)
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:123)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$54(LanguageWorker.java:172)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:29)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:146)
	at java.lang.Thread.run(Unknown Source)
00:01  INFO: Building mpq
00:01  INFO: Sorted blocks
00:01  INFO: Added existing files
00:01  INFO: Added new files
00:01  INFO: Added listfile
00:01  INFO: Rebuild complete. Took: 16ms
2017-11-20 10:20:38 SEVERE Internal error: java.lang.RuntimeException: There was a Wurst bug in the translation of variable b (D:\Download\MyWurstProject\wurst\Hello.wurst:5): cannot translate array type integer array(dimensions = 1) array(dimensions = 1)  array integer
Please open a ticket with source code and the error log.
java.util.concurrent.CompletionException: java.lang.RuntimeException: There was a Wurst bug in the translation of variable b (D:\Download\MyWurstProject\wurst\Hello.wurst:5): cannot translate array type integer array(dimensions = 1) array(dimensions = 1)  array integer
Please open a ticket with source code and the error log.
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.handleException(UserRequest.java:40)
	at de.peeeq.wurstio.languageserver.requests.RunMap.handleException(RunMap.java:88)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$handle$56(LanguageWorker.java:275)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:34)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$54(LanguageWorker.java:172)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:29)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:146)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: There was a Wurst bug in the translation of variable b (D:\Download\MyWurstProject\wurst\Hello.wurst:5): cannot translate array type integer array(dimensions = 1) array(dimensions = 1)  array integer
Please open a ticket with source code and the error log.
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.translateProg(ImTranslator.java:138)
	at de.peeeq.wurstio.WurstCompilerJassImpl.translateProgToIm(WurstCompilerJassImpl.java:458)
	at de.peeeq.wurstio.languageserver.requests.RunMap.compileScript(RunMap.java:283)
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:123)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	... 4 more
Caused by: java.lang.Error: cannot translate array type integer array(dimensions = 1) array(dimensions = 1)  array integer
	at de.peeeq.wurstscript.types.WurstTypeArray.imTranslateType(WurstTypeArray.java:89)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.getVarFor(ImTranslator.java:743)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translateVar(TLDTranslation.java:20)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:27)
	at de.peeeq.wurstscript.ast.GlobalVarDefImpl.imTranslateEntity(GlobalVarDefImpl.java:369)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:59)
	at de.peeeq.wurstscript.ast.WPackageImpl.imTranslateTLD(WPackageImpl.java:402)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.translateCompilationUnit(ImTranslator.java:303)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.translateProg(ImTranslator.java:118)
	... 8 more

**Comment by Frotty** [comment]
It's not allowed. Just needs a proper error.
