### ISSUE TITLE
Tertiary operator crashes compilation

### ISSUE THREAD

**Issue by Trokkin** [wurstscript/WurstScript#606]
So, with all my love to hurry and bad code style, I've discovered a weird bug:
`Filter( () -> ( someBool ? someUnit.setPos(someVec2) : false ) )`
forces compilation to an unhandled error:
> 2017-12-22 19:05:01 INFO   translating program to jass ... 
2017-12-22 19:05:01 INFO   progress: Translating wurst. Phase 2: translate classes
2017-12-22 19:05:01 INFO   progress: Translating wurst. Phase 4: add stack traces
2017-12-22 19:05:03 INFO   progress: Translating wurst. Phase 6: eliminate tuples
2017-12-22 19:02:41 SEVERE Error
java.lang.Error: unhandled case: class de.peeeq.wurstscript.jassIm.ImFunctionCallImpl
	at de.peeeq.wurstscript.translation.imtranslation.EliminateTuples.eliminateTuples(EliminateTuples.java:236)
	at de.peeeq.wurstscript.jassIm.ImSetImpl.eliminateTuples(ImSetImpl.java:173)
	at de.peeeq.wurstscript.translation.imtranslation.EliminateTuples.transformStatements(EliminateTuples.java:90)
	at de.peeeq.wurstscript.translation.imtranslation.EliminateTuples.eliminateTuplesDispatch(EliminateTuples.java:152)
	at de.peeeq.wurstscript.translation.imtranslation.EliminateTuples.eliminateTuples2(EliminateTuples.java:134)
	at de.peeeq.wurstscript.translation.imtranslation.EliminateTuples.eliminateTuples(EliminateTuples.java:164)
	at de.peeeq.wurstscript.jassIm.ImIfImpl.eliminateTuples(ImIfImpl.java:184)
	at de.peeeq.wurstscript.translation.imtranslation.EliminateTuples.transformStatements(EliminateTuples.java:90)
	at de.peeeq.wurstscript.translation.imtranslation.EliminateTuples.eliminateTuplesProg(EliminateTuples.java:31)
	at de.peeeq.wurstscript.jassIm.ImProgImpl.eliminateTuples(ImProgImpl.java:158)
	at de.peeeq.wurstio.WurstCompilerJassImpl.transformProgToJass(WurstCompilerJassImpl.java:377)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.compileMap(MapRequest.java:155)
	at de.peeeq.wurstio.languageserver.requests.RunMap.compileScript(RunMap.java:232)
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:79)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$71(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.lang.Thread.run(Thread.java:748)

**Comment by IgorSamurovic** [comment]
Basically, it seems that ternary operator here doesn't check the return value of unit.setPos(vec2 pos), and doesn't notify the user, instead it crashes the language server on compilation.

**Comment by Frotty** [comment]
well yea, this is errornous code since .setPos() doesn't return boolean. You need to fix your code, but ofc there should be an error instead of exception. Thanks for report.
