### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by DDLegionTN** [wurstscript/WurstScript#612]
![image](https://user-images.githubusercontent.com/10547551/34647680-ababd780-f3c3-11e7-8a1f-347043ed7390.png)

To reproduce :
1. Open Visual Studio
2. Open your project
3. Open your project map (ExampleMap.w3x) from WE (Mine is with SharpCraft)
4. (Save map at least once) and close your WE (close WE, not close map)
5. Build/Run ExampleMap.w3x from VS

```
01:05  INFO: Building mpq
01:05  INFO: Sorted blocks
01:05  INFO: Added existing files
01:05  INFO: Added new files
01:05  INFO: Added listfile
01:05  INFO: Rebuild complete. Took: 17ms
01:05  INFO: Building mpq
01:05  INFO: Sorted blocks
01:05  INFO: Added existing files
01:05  INFO: Added new files
01:05  INFO: Added listfile
01:05  INFO: Rebuild complete. Took: 11ms
Jan 07, 2018 3:58:25 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint lambda$static$0
SEVERE: Internal error: java.lang.RuntimeException: java.io.IOException: The system cannot find the path specified
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.IOException: The system cannot find the path specified
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.handleException(UserRequest.java:40)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.handleException(MapRequest.java:64)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$handle$73(LanguageWorker.java:272)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:34)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$71(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.io.IOException: The system cannot find the path specified
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:118)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	... 4 more
Caused by: java.io.IOException: The system cannot find the path specified
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(Unknown Source)
	at de.peeeq.wurstio.mpq.Jmpq3BasedEditor.insertFile(Jmpq3BasedEditor.java:36)
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:94)
	... 5 more
```

**Comment by IgorSamurovic** [comment]
Cannot reproduce this, I always edit the map in WE, then run it. Are you missing some steps?

**Comment by Frotty** [comment]
Try running vscode as admin

**Comment by DDLegionTN** [comment]
Sorry for the late update, the reproduction step is lacking 1 step which i wasn't aware when trying to reproduce. The full steps would be :
1. Open your project (ExampleMap.w3x)
2. Build map
3. Open map (ExampleMap.w3x) in WE
4. Save and close WE
5. Build map again

That time the compiler was at 588. Now it is fixed, after updated to 589, with https://github.com/wurstscript/WurstScript/commit/6ea3b5bb7a7af79b313d1742d7ebff6d9e9b0ee7
