### ISSUE TITLE
Exception in Wurst setup

### ISSUE THREAD

**Issue by texel-sensei** [wurstscript/WurstScript#621]
When I start the WurstSetup.jar the following exception occurs:
```
Please report this crash with the following info:
Version: 1.1.4.0-jenkins-WurstSetup-50
us.monoid.json.JSONException: JSONObject["buildsByBranchName"] not found.
	at us.monoid.json.JSONObject.get(JSONObject.java:419)
	at us.monoid.web.jp.javacc.JSONPathCompiler$JSONPathExpr.eval(JSONPathCompiler.java:74)
	at us.monoid.web.jp.javacc.JSONPathCompiler$JSONPathExpr.eval(JSONPathCompiler.java:40)
	at us.monoid.web.jp.javacc.JSONPathCompiler$JSONPathExpr.eval(JSONPathCompiler.java:40)
	at us.monoid.web.JSONPathQuery.eval(JSONPathQuery.java:42)
	at us.monoid.web.JSONResource.get(JSONResource.java:130)
	at net.ConnectionManager.getJson(ConnectionManager.kt:24)
	at net.ConnectionManager.getBuildNumber(ConnectionManager.kt:64)
	at net.ConnectionManager.getLatestCompilerBuild(ConnectionManager.kt:79)
	at global.InstallationManager.verifyInstallation(InstallationManager.kt:50)
	at file.SetupApp.startup(SetupApp.kt:86)
	at file.SetupApp.handleArgs(SetupApp.kt:22)
	at file.SetupMain.doMain(SetupMain.kt:54)
	at file.SetupMain$Companion.main(SetupMain.kt:61)
	at file.SetupMain.main(SetupMain.kt)
```

I'm using java version 1.8.0_152.

**Comment by Frotty** [comment]
see https://github.com/wurstscript/WurstSetup/issues/3
