### ISSUE TITLE
sorry，I can t use it i m from China....

### ISSUE THREAD

**Issue by hzj61002963** [wurstscript/WurstScript#630]
Please report this crash with the following info:
Version: 1.1.4.0-jenkins-WurstSetup-54
java.security.PrivilegedActionException: java.util.zip.ZipException: error in opening zip file
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at file.ZipArchiveExtractor.extractArchive(ZipArchiveExtractor.kt:27)
	at global.InstallationManager$handleUpdate$1.invoke(InstallationManager.kt:103)
	at global.InstallationManager$handleUpdate$1.invoke(InstallationManager.kt:19)
	at workers.DownloadWithProgressWorker.done(DownloadWithProgressWorker.kt:56)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	... 9 more

**Comment by Frotty** [comment]
This is a setup issue. Moving to correct project.

**Comment by Frotty** [comment]
This issue was moved to wurstscript/WurstSetup#9
