### ISSUE TITLE
Conditional operator + sized array inside the class = Error

### ISSUE THREAD

**Issue by vitalexbel** [wurstscript/WurstScript#631]
this works fine:
```
bool cond = true

class TestClass

	function ffff() returns int
		return cond ? 1 : 0
```
and this works fine:
```
bool cond = true

class TestClass
	int array[3] zzzz

	function ffff() returns int
		if cond
			return zzzz[1]
		return 0
```
and this also works fine:
```
bool cond = true
int array zzzz

class TestClass
	
	function ffff() returns int
		return cond ? zzzz[1] : 0
```
**ERROR: ▼ ▼ ▼**
```
bool cond = true

class TestClass
	int array[3] zzzz

	function ffff() returns int
		return cond ? zzzz[1] : 0
```
log:
```
2018-03-18 22:40:25 [Wurst LanguageWorker] INFO  languageServer - progress: Check program 
2018-03-18 22:40:25 [Wurst LanguageWorker] INFO  languageServer - progress: Checking Files 
2018-03-18 22:40:25 [Wurst LanguageWorker] INFO  languageServer - progress: Checking wurst types 
2018-03-18 22:40:25 [Wurst LanguageWorker] INFO  languageServer - progress: Post checks 
2018-03-18 22:40:25 [Wurst LanguageWorker] INFO  languageServer - debug - finished checkProg 
2018-03-18 22:40:25 [Wurst LanguageWorker] INFO  languageServer - translating program ...  
2018-03-18 22:40:25 [Wurst LanguageWorker] INFO  languageServer - progress: Translating wurst. Phase 1: to intermediate lang 
2018-03-18 22:40:25 [Wurst LanguageWorker] ERROR languageServer - Error 
java.lang.Error: not implemented
	at de.peeeq.wurstscript.translation.imtojass.ImAttrType.getType(ImAttrType.java:151)
	at de.peeeq.wurstscript.jassIm.ImVarArrayMultiAccessImpl.attrTyp(ImVarArrayMultiAccessImpl.java:226)
	at de.peeeq.wurstscript.translation.imtranslation.ExprTranslation.translate(ExprTranslation.java:619)
	at de.peeeq.wurstscript.ast.ExprIfElseImpl.imTranslateExprOpt(ExprIfElseImpl.java:339)
	at de.peeeq.wurstscript.translation.imtranslation.StmtTranslation.translate(StmtTranslation.java:130)
	at de.peeeq.wurstscript.ast.StmtReturnImpl.imTranslateStmt(StmtReturnImpl.java:264)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.translateStatements(ImTranslator.java:784)
	at de.peeeq.wurstscript.translation.imtranslation.ClassTranslator.createStaticCallFunc(ClassTranslator.java:336)
	at de.peeeq.wurstscript.translation.imtranslation.ClassTranslator.translateMethod(ClassTranslator.java:280)
	at de.peeeq.wurstscript.translation.imtranslation.ClassTranslator.translateMethods(ClassTranslator.java:272)
	at de.peeeq.wurstscript.translation.imtranslation.ClassTranslator.translate(ClassTranslator.java:74)
	at de.peeeq.wurstscript.translation.imtranslation.ClassTranslator.translate(ClassTranslator.java:47)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:71)
	at de.peeeq.wurstscript.ast.ClassDefImpl.imTranslateEntity(ClassDefImpl.java:646)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:59)
	at de.peeeq.wurstscript.ast.WPackageImpl.imTranslateTLD(WPackageImpl.java:407)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.translateCompilationUnit(ImTranslator.java:307)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.translateProg(ImTranslator.java:118)
	at de.peeeq.wurstio.WurstCompilerJassImpl.translateProgToIm(WurstCompilerJassImpl.java:459)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.compileMap(MapRequest.java:129)
	at de.peeeq.wurstio.languageserver.requests.BuildMap.compileScript(BuildMap.java:196)
	at de.peeeq.wurstio.languageserver.requests.BuildMap.execute(BuildMap.java:86)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$75(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.lang.Thread.run(Unknown Source)
2018-03-18 22:40:25 [Wurst LanguageWorker] INFO  languageServer - progress: Injecting mapscript 
```

**Comment by Frotty** [comment]
Yea, currently `not implemented`, might be related to the current type reworks.
