### ISSUE TITLE
single wurst file cannot contain more than 2000 chars?

### ISSUE THREAD

**Issue by lhing17** [wurstscript/WurstScript#642]
When I wrote more than 2000 (I don't know the exact num, seems to be 2000) chars in a single wurst file, I got a StringIndexOutOfBoundsException in output of wurstLanguageServer in my VSCode, the stacktrace info is as follows:

```
Internal error: java.lang.StringIndexOutOfBoundsException: String index out of range: 2087
java.util.concurrent.CompletionException: java.lang.StringIndexOutOfBoundsException: String index out of range: 2087
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.handleException(UserRequest.java:40)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$handle$77(LanguageWorker.java:272)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:34)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$75(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 2087
	at java.lang.String.<init>(String.java:205)
	at org.antlr.v4.runtime.CodePointCharStream$CodePoint16BitCharStream.getText(CodePointCharStream.java:215)
	at de.peeeq.wurstscript.WurstParser$1.syntaxError(WurstParser.java:84)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportUnwantedToken(DefaultErrorStrategy.java:349)
	at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:247)
	at de.peeeq.wurstscript.antlr.WurstParser.wpackage(WurstParser.java:1564)
	at de.peeeq.wurstscript.antlr.WurstParser.topLevelDeclaration(WurstParser.java:290)
	at de.peeeq.wurstscript.antlr.WurstParser.compilationUnit(WurstParser.java:237)
	at de.peeeq.wurstscript.WurstParser.parseWithAntlr(WurstParser.java:101)
	at de.peeeq.wurstscript.WurstParser.parse(WurstParser.java:38)
	at de.peeeq.wurstio.WurstCompilerJassImpl.parse(WurstCompilerJassImpl.java:604)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.replaceCompilationUnit(ModelManagerImpl.java:463)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.replaceCompilationUnitContent(ModelManagerImpl.java:436)
	at de.peeeq.wurstio.languageserver.requests.HoverInfo.execute(HoverInfo.java:40)
	at de.peeeq.wurstio.languageserver.requests.HoverInfo.execute(HoverInfo.java:23)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	... 4 more
```

**Comment by Frotty** [comment]
The log says it happens in HoverInfo and has nothing to do with the length of the file.
Post the code, it looks like a Unicode issue.
There are packages with 100K chars int he stdlib, so obviously that's not the problem.

**Comment by lhing17** [comment]
I found the exception disappeared when I corrected all the syntax error, but kept output in the console during my writing... Talking about the Unicode issue, Indeed I used some Chinese characters in the comments. The problem is, the char number showed in the error prompt (ie.,  String index out of range: 2087) is exactly the length of my wurst file. Here is the example code:

`package Common

import GameConfiguration
import Hero

/** 获取玩家人数 **/
public function getPlayerNumber() returns integer
    var n = 0
    for i = 0 to MAX_PLAYER_NUMBER - 1
        if Player(i).getController() == MAP_CONTROL_USER and Player(i).getSlotState() == PLAYER_SLOT_STATE_PLAYING
            n++
    return n

public function unit.isEnemyOf(player p) returns bool
    return this.getOwner().isEnemyOf(p)

public function unit.isEnemyOf(unit u) returns bool
    return this.isEnemyOf(u.getOwner())

public function percentPossiblity(real r) returns bool
    return GetRandomReal(0, 100) < r

/** 攻击者拥有某技能并且是触发单位的敌人，通常用于被动技能 **/
public function unitHasAbilityAndIsEnemy(unit attacker, unit triggerUnit, int abilityId) returns bool
    return attacker.hasAbility(abilityId) and attacker.isEnemyOf(triggerUnit)

/** 马甲单位对目标施放技能 **/
public function dummyUnitCastAbilityTarget(player owner, int abilityId, int lvl, int orderId, widget target, vec2 casterPos)
    let u = createUnit(owner, 'e000', casterPos, casterPos.angleTo(target.getPos()))
    u.hide()
    u.addAbility(abilityId)
    u.setAbilityLevel(abilityId, lvl)
    u.issueTargetOrderById(orderId, target)
    u.setTimedLife(3)

/** 马甲单位对点施放技能 **/
public function dummyUnitCastAbilityPos(player owner, int abilityId, int lvl, int orderId, vec2 targetPos, vec2 casterPos)
    let u = createUnit(owner, 'e000', casterPos, casterPos.angleTo(targetPos))
    u.hide()
    u.addAbility(abilityId)
    u.setAbilityLevel(abilityId, lvl)  
    u.issuePointOrderById(orderId, targetPos)
    u.setTimedLife(3)

/** 造成伤害 **/
public function applyDamage(unit source, unit target, real damage)
    if damage == 0
        createTTEx(target.getPos3Real(), vec2(400, GetRandomReal(80.,100.)), "MISS", 11, 0.65, colorA(255, 0, 0, 30))
    else
        source.damageTarget(target, damage)
        if GetRandomReal(0, 100) <= 100 * source.getHero().criticalRate
            createTTEx(target.getPos3Real(), vec2(400, GetRandomReal(80.,100.)), damage.toInt().toString(), 14, 0.65, colorA(100, 100, 0, 30))
        else
            createTTEx(target.getPos3Real(), vec2(400, GetRandomReal(80.,100.)), damage.toInt().toString(), 11, 0.65, colorA(100, 100, 100, 30))

public function getPosFromPos(vec2 pos, real range, angle ang) returns vec2
    var x = pos.x + range * ang.cos()
    var y = pos.y + range * ang.sin()
    return vec2(x, y)`

**Comment by Frotty** [comment]
Hi, you need to be more precise. The package contains imports that I don't have. I removed the stuff and I don't get any error with this package.
Please create a new project, and try to re-create the problem with as little code as possible.
Then write a step by step guide on how to make it happen.
![](https://i.imgur.com/JgR2R91.png)

Some other tips on your code:
`Player(i) -> players[i]`
```
u.xx()
u.yy()
u.zz()
```
->
```
u.xx()
..yy()
..zz()
```
In `dummyUnitCastAbilityPos` you don't even need the variable `u` this way.
Also, are you aware on `InstantDummyCaster` package?

`getPosFromPos` already exists as `vec2.polarOffset` you are just duplicating code here, in worse.

**Comment by Frotty** [comment]
Okay I also got the exception when I added extra code. I added a simple assertion and it seems to work now. Update your compiler and report back.

**Comment by lhing17** [comment]
Thanks for your update and kind tip. It seems to work after the compiler update.
