### ISSUE TITLE
"must not happen" error happens

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#676]
```
java.lang.Error: Cannot find namelink for function <getPos>
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.getClassesWithImplementation(ImTranslator.java:903)
	at de.peeeq.wurstscript.translation.imtranslation.ClassTranslator.translateMethod(ClassTranslator.java:292)
	at de.peeeq.wurstscript.translation.imtranslation.ClassTranslator.translateMethods(ClassTranslator.java:274)
	at de.peeeq.wurstscript.translation.imtranslation.ClassTranslator.translate(ClassTranslator.java:75)
	at de.peeeq.wurstscript.translation.imtranslation.ClassTranslator.translate(ClassTranslator.java:48)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:75)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:73)
	at de.peeeq.wurstscript.ast.ClassDefImpl.imTranslateEntity(ClassDefImpl.java:634)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:61)
	at de.peeeq.wurstscript.ast.WPackageImpl.imTranslateTLD(WPackageImpl.java:411)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:54)
	at de.peeeq.wurstscript.ast.WPackageImpl.imTranslateTLD(WPackageImpl.java:411)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:54)
	at de.peeeq.wurstscript.ast.WPackageImpl.imTranslateTLD(WPackageImpl.java:411)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:54)
	at de.peeeq.wurstscript.ast.WPackageImpl.imTranslateTLD(WPackageImpl.java:411)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:54)
	at de.peeeq.wurstscript.ast.WPackageImpl.imTranslateTLD(WPackageImpl.java:411)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.translateCompilationUnit(ImTranslator.java:310)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.translateProg(ImTranslator.java:119)
	at de.peeeq.wurstio.WurstCompilerJassImpl.translateProgToIm(WurstCompilerJassImpl.java:462)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.compileMap(MapRequest.java:129)
	at de.peeeq.wurstio.languageserver.requests.RunMap.compileScript(RunMap.java:235)
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:83)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.lang.Thread.run(Unknown Source)
Jun 16, 2018 9:07:38 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.RuntimeException: java.lang.RuntimeException: There was a Wurst bug in the translation of endfunctionstatement  (C:\Users\Frotty\Documents\GitHub\ForestDef2\_build\dependencies\frentity\wurst\entity\Entity.wurst:104): Cannot find namelink for function <getPos>
Please open a ticket with source code and the error log.
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.RuntimeException: There was a Wurst bug in the translation of endfunctionstatement  (C:\Users\Frotty\Documents\GitHub\ForestDef2\_build\dependencies\frentity\wurst\entity\Entity.wurst:104): Cannot find namelink for function <getPos>
Please open a ticket with source code and the error log.
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.handleException(UserRequest.java:40)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.handleException(MapRequest.java:63)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$handle$3(LanguageWorker.java:272)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:34)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: There was a Wurst bug in the translation of endfunctionstatement  (C:\Users\Frotty\Documents\GitHub\ForestDef2\_build\dependencies\frentity\wurst\entity\Entity.wurst:104): Cannot find namelink for function <getPos>
Please open a ticket with source code and the error log.
	at de.peeeq.wurstio.languageserver.requests.MapRequest.compileMap(MapRequest.java:177)
	at de.peeeq.wurstio.languageserver.requests.RunMap.compileScript(RunMap.java:235)
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:83)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	... 4 more
Caused by: java.lang.RuntimeException: There was a Wurst bug in the translation of endfunctionstatement  (C:\Users\Frotty\Documents\GitHub\ForestDef2\_build\dependencies\frentity\wurst\entity\Entity.wurst:104): Cannot find namelink for function <getPos>
Please open a ticket with source code and the error log.
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.translateProg(ImTranslator.java:140)
	at de.peeeq.wurstio.WurstCompilerJassImpl.translateProgToIm(WurstCompilerJassImpl.java:462)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.compileMap(MapRequest.java:129)
	... 7 more
Caused by: java.lang.Error: Cannot find namelink for function <getPos>
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.getClassesWithImplementation(ImTranslator.java:903)
	at de.peeeq.wurstscript.translation.imtranslation.ClassTranslator.translateMethod(ClassTranslator.java:292)
	at de.peeeq.wurstscript.translation.imtranslation.ClassTranslator.translateMethods(ClassTranslator.java:274)
	at de.peeeq.wurstscript.translation.imtranslation.ClassTranslator.translate(ClassTranslator.java:75)
	at de.peeeq.wurstscript.translation.imtranslation.ClassTranslator.translate(ClassTranslator.java:48)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:75)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:73)
	at de.peeeq.wurstscript.ast.ClassDefImpl.imTranslateEntity(ClassDefImpl.java:634)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:61)
	at de.peeeq.wurstscript.ast.WPackageImpl.imTranslateTLD(WPackageImpl.java:411)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:54)
	at de.peeeq.wurstscript.ast.WPackageImpl.imTranslateTLD(WPackageImpl.java:411)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:54)
	at de.peeeq.wurstscript.ast.WPackageImpl.imTranslateTLD(WPackageImpl.java:411)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:54)
	at de.peeeq.wurstscript.ast.WPackageImpl.imTranslateTLD(WPackageImpl.java:411)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:54)
	at de.peeeq.wurstscript.ast.WPackageImpl.imTranslateTLD(WPackageImpl.java:411)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.translateCompilationUnit(ImTranslator.java:310)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.translateProg(ImTranslator.java:119)
	... 9 more

``` 

Source: https://github.com/Frotty/Frentity/blob/master/wurst/entity/Entity.wurst#L104

**Comment by Frotty** [comment]
@peq
