### ISSUE TITLE
Wurst and w3x2ini are not compatible

### ISSUE THREAD

**Issue by supemeko** [wurstscript/WurstScript#685]
Unable to open this map
[ExampleMap.zip](https://github.com/wurstscript/WurstScript/files/2174732/ExampleMap.zip)

Unable to open this map using wurst after packaging with w3x2ini

**Comment by supemeko** [comment]
w3x2ini : https://github.com/sumneko/w3x2lni

**Comment by Frotty** [comment]
Just like the YDWE tickets before, this isn't a wurst issue...
Wurst builds maps which can be read by all other tools.
If Wurst can't read the map by another tool, that .mpq is broken/corrupted/protected

We don't support protected maps. Ask the creator of w3x3lni to fix this or make a PR on our mpq lib https://github.com/inwc3/JMPQ3

**Comment by supemeko** [comment]
But the original WE can open the map.

**Comment by supemeko** [comment]
Regarding the issue template, I don't know how to do it.
I will re-save the map using the original WE and it can be opened by the wurst.
Thank you for your reply。

**Comment by Frotty** [comment]
Navigate to your user folder, and go to the `.wurst` folder. In there, there is a `logs` folder which contains the data. Copy the last 100 lines or so into a code block:
````
Like This
````

If the issue happens on buildmap/runmap, the error will also be printed in vscode, under the output tab -> wurstLangServer

**Comment by peq** [comment]
For reference: Stacktrace when compiling the Map attached in the first post.

```
SEVERE: Internal error: java.lang.RuntimeException: java.nio.BufferOverflowException
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.nio.BufferOverflowException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.handleException(UserRequest.java:40)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.handleException(MapRequest.java:63)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$handle$3(LanguageWorker.java:272)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:34)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.RuntimeException: java.nio.BufferOverflowException
	at de.peeeq.wurstio.languageserver.requests.MapRequest.compileMap(MapRequest.java:177)
	at de.peeeq.wurstio.languageserver.requests.BuildMap.compileScript(BuildMap.java:171)
	at de.peeeq.wurstio.languageserver.requests.BuildMap.execute(BuildMap.java:79)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	... 4 more
Caused by: java.nio.BufferOverflowException
	at java.base/java.nio.DirectByteBuffer.put(DirectByteBuffer.java:381)
	at java.base/java.nio.ByteBuffer.put(ByteBuffer.java:899)
	at systems.crigges.jmpq3.MpqFile.writeFileAndBlock(MpqFile.java:204)
	at systems.crigges.jmpq3.JMpqEditor.close(JMpqEditor.java:745)
	at systems.crigges.jmpq3.JMpqEditor.close(JMpqEditor.java:664)
	at de.peeeq.wurstio.mpq.Jmpq3BasedEditor.close(Jmpq3BasedEditor.java:61)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.compileMap(MapRequest.java:176)
	... 7 more
```

**Comment by Frotty** [comment]
Yeah, normal jmpq behaviour on invalid header/table data

**Comment by Frotty** [comment]
Hey, due to recent updates to jmpq by the amazing @WaterKnight and me, maps like these should now be fully supported by wurstscript 😎 

@supemeko Can you please update wurst and verify this?

Cheers 🍻
