### ISSUE TITLE
Implementing an abstract class causes mayhem

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#704]
```
abstract class A

	construct(int i)

class B implements A
```

Spams a load of exceptions:
```
java.lang.ClassCastException: de.peeeq.wurstscript.types.WurstTypeClass cannot be cast to de.peeeq.wurstscript.types.WurstTypeInterface
java.lang.ClassCastException: de.peeeq.wurstscript.types.WurstTypeClass cannot be cast to de.peeeq.wurstscript.types.WurstTypeInterface
de.peeeq.wurstscript.types.WurstTypeClass.lambda$implementedInterfaces$0(WurstTypeClass.java:65)
java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
java.util.ArrayList$Itr.forEachRemaining(Unknown Source)
java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
java.util.stream.AbstractPipeline.copyInto(Unknown Source)
java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
java.util.stream.AbstractPipeline.evaluate(Unknown Source)
java.util.stream.ReferencePipeline.collect(Unknown Source)
de.peeeq.wurstscript.types.WurstTypeClass.implementedInterfaces(WurstTypeClass.java:67)
de.peeeq.wurstscript.attributes.names.NameLinks.addNamesFromImplementedInterfaces(NameLinks.java:110)
de.peeeq.wurstscript.attributes.names.NameLinks.calculate(NameLinks.java:48)
de.peeeq.wurstscript.ast.ClassDefImpl.attrNameLinks(ClassDefImpl.java:673)
de.peeeq.wurstscript.attributes.names.NameLinks.calculate(NameLinks.java:242)
de.peeeq.wurstscript.ast.WEntitiesImpl.attrNameLinks(WEntitiesImpl.java:188)
de.peeeq.wurstscript.attributes.names.Exports.addExportedNameLinks(Exports.java:35)
de.peeeq.wurstscript.attributes.names.Exports.exportedNameLinks(Exports.java:20)
de.peeeq.wurstscript.ast.WPackageImpl.attrExportedNameLinks(WPackageImpl.java:460)
de.peeeq.wurstscript.attributes.names.NameLinks.calculate(NameLinks.java:219)
de.peeeq.wurstscript.ast.WPackageImpl.attrNameLinks(WPackageImpl.java:432)
de.peeeq.wurstscript.validation.WurstValidator.checkForDuplicateNames(WurstValidator.java:2156)
de.peeeq.wurstscript.validation.WurstValidator.check(WurstValidator.java:329)
de.peeeq.wurstscript.validation.WurstValidator.walkTree(WurstValidator.java:209)
de.peeeq.wurstscript.validation.WurstValidator.walkTree(WurstValidator.java:212)
de.peeeq.wurstscript.validation.WurstValidator.walkTree(WurstValidator.java:212)
de.peeeq.wurstscript.validation.WurstValidator.validate(WurstValidator.java:60)
de.peeeq.wurstscript.WurstChecker.checkProg(WurstChecker.java:46)
de.peeeq.wurstio.WurstCompilerJassImpl.checkProg(WurstCompilerJassImpl.java:326)
de.peeeq.wurstio.languageserver.ModelManagerImpl.doTypeCheckPartial(ModelManagerImpl.java:551)
de.peeeq.wurstio.languageserver.ModelManagerImpl.syncCompilationUnitContent(ModelManagerImpl.java:439)
de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$2(LanguageWorker.java:185)
de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
java.lang.Thread.run(Unknown Source)
```
```
SEVERE: Internal error: java.lang.RuntimeException: java.lang.NullPointerException
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.handleException(UserRequest.java:40)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.handleException(MapRequest.java:63)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$handle$3(LanguageWorker.java:272)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:34)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at de.peeeq.wurstio.languageserver.requests.BuildMap.applyProjectConfig(BuildMap.java:129)
	at de.peeeq.wurstio.languageserver.requests.BuildMap.execute(BuildMap.java:97)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	... 4 more
Caused by: java.lang.NullPointerException
	at net.moonlightflower.wc3libs.bin.app.W3I.write_0x19(W3I.java:2027)
	at net.moonlightflower.wc3libs.bin.app.W3I.write(W3I.java:2122)
	at net.moonlightflower.wc3libs.bin.app.W3I.write(W3I.java:2139)
	at net.moonlightflower.wc3libs.bin.app.W3I.write(W3I.java:2145)
	at de.peeeq.wurstio.languageserver.requests.BuildMap.applyProjectConfig(BuildMap.java:123)
	... 6 more

java.lang.ClassCastException
java.lang.ClassCastException
java.lang.ClassCastException
java.lang.ClassCastException
java.lang.ClassCastException
java.lang.ClassCastException
java.lang.ClassCastException
java.lang.ClassCastException
java.lang.ClassCastException
Aug 05, 2018 9:04:42 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: de.peeeq.wurstscript.ast.CyclicDependencyError
java.util.concurrent.CompletionException: de.peeeq.wurstscript.ast.CyclicDependencyError
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.handleException(UserRequest.java:40)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$handle$3(LanguageWorker.java:272)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:34)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.lang.Thread.run(Unknown Source)
Caused by: de.peeeq.wurstscript.ast.CyclicDependencyError
	at de.peeeq.wurstscript.ast.ClassDefImpl.attrNameLinks(ClassDefImpl.java:676)
	at de.peeeq.wurstio.languageserver.requests.GetCompletions.addDefaultCompletions(GetCompletions.java:292)
	at de.peeeq.wurstio.languageserver.requests.GetCompletions.calculateCompletions(GetCompletions.java:219)
	at de.peeeq.wurstio.languageserver.requests.GetCompletions.computeCompletionProposals(GetCompletions.java:117)
	at de.peeeq.wurstio.languageserver.requests.GetCompletions.execute(GetCompletions.java:73)
	at de.peeeq.wurstio.languageserver.requests.GetCompletions.execute(GetCompletions.java:33)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	... 4 more

[Error - 21:04:42] Request textDocument/completion failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: de.peeeq.wurstscript.ast.CyclicDependencyError
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.handleException(UserRequest.java:40)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$handle$3(LanguageWorker.java:272)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:34)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.lang.Thread.run(Unknown Source)
Caused by: de.peeeq.wurstscript.ast.CyclicDependencyError
	at de.peeeq.wurstscript.ast.ClassDefImpl.attrNameLinks(ClassDefImpl.java:676)
	at de.peeeq.wurstio.languageserver.requests.GetCompletions.addDefaultCompletions(GetCompletions.java:292)
	at de.peeeq.wurstio.languageserver.requests.GetCompletions.calculateCompletions(GetCompletions.java:219)
	at de.peeeq.wurstio.languageserver.requests.GetCompletions.computeCompletionProposals(GetCompletions.java:117)
	at de.peeeq.wurstio.languageserver.requests.GetCompletions.execute(GetCompletions.java:73)
	at de.peeeq.wurstio.languageserver.requests.GetCompletions.execute(GetCompletions.java:33)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	... 4 more

Aug 05, 2018 9:04:45 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: de.peeeq.wurstscript.ast.CyclicDependencyError
java.util.concurrent.CompletionException: de.peeeq.wurstscript.ast.CyclicDependencyError
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.handleException(UserRequest.java:40)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$handle$3(LanguageWorker.java:272)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:34)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.lang.Thread.run(Unknown Source)
Caused by: de.peeeq.wurstscript.ast.CyclicDependencyError
	at de.peeeq.wurstscript.ast.WEntitiesImpl.attrNameLinks(WEntitiesImpl.java:191)
	at de.peeeq.wurstscript.attributes.names.NameResolution.lookupFuncsNoConfig(NameResolution.java:36)
	at de.peeeq.wurstscript.ast.ExprFunctionCallImpl.lookupFuncsNoConfig(ExprFunctionCallImpl.java:582)
	at de.peeeq.wurstscript.attributes.names.NameResolution.lookupFuncs(NameResolution.java:49)
	at de.peeeq.wurstscript.attributes.names.NameResolution.lookupFuncsShort(NameResolution.java:269)
	at de.peeeq.wurstscript.ast.ExprFunctionCallImpl.lookupFuncs(ExprFunctionCallImpl.java:606)
	at de.peeeq.wurstscript.attributes.PossibleFuncDefs.searchFunction(PossibleFuncDefs.java:87)
	at de.peeeq.wurstscript.attributes.PossibleFuncDefs.calculate(PossibleFuncDefs.java:55)
	at de.peeeq.wurstscript.ast.ExprFunctionCallImpl.attrPossibleFuncDefs(ExprFunctionCallImpl.java:531)
	at de.peeeq.wurstscript.attributes.AttrPossibleFunctionSignatures.calculate(AttrPossibleFunctionSignatures.java:25)
	at de.peeeq.wurstscript.ast.ExprFunctionCallImpl.attrPossibleFunctionSignatures(ExprFunctionCallImpl.java:453)
	at de.peeeq.wurstscript.attributes.AttrFunctionSignature.calculate(AttrFunctionSignature.java:16)
	at de.peeeq.wurstscript.ast.ExprFunctionCallImpl.attrFunctionSignature(ExprFunctionCallImpl.java:467)
	at de.peeeq.wurstscript.attributes.AttrExprType.calculate(AttrExprType.java:413)
	at de.peeeq.wurstscript.ast.ExprFunctionCallImpl.attrTypRaw(ExprFunctionCallImpl.java:341)
	at de.peeeq.wurstscript.attributes.AttrExprType.normalizedType(AttrExprType.java:507)
	at de.peeeq.wurstscript.ast.ExprFunctionCallImpl.attrTyp(ExprFunctionCallImpl.java:313)
	at de.peeeq.wurstscript.attributes.PossibleFuncDefs.calculate(PossibleFuncDefs.java:48)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrPossibleFuncDefs(ExprMemberMethodDotDotImpl.java:569)
	at de.peeeq.wurstscript.attributes.AttrPossibleFunctionSignatures.calculate(AttrPossibleFunctionSignatures.java:25)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrPossibleFunctionSignatures(ExprMemberMethodDotDotImpl.java:491)
	at de.peeeq.wurstscript.attributes.AttrFunctionSignature.calculate(AttrFunctionSignature.java:16)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrFunctionSignature(ExprMemberMethodDotDotImpl.java:505)
	at de.peeeq.wurstscript.attributes.AttrExprType.calculate(AttrExprType.java:550)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrTypRaw(ExprMemberMethodDotDotImpl.java:379)
	at de.peeeq.wurstscript.attributes.AttrExprType.normalizedType(AttrExprType.java:507)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrTyp(ExprMemberMethodDotDotImpl.java:351)
	at de.peeeq.wurstscript.attributes.PossibleFuncDefs.calculate(PossibleFuncDefs.java:48)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotImpl.attrPossibleFuncDefs(ExprMemberMethodDotImpl.java:569)
	at de.peeeq.wurstscript.attributes.AttrPossibleFunctionSignatures.calculate(AttrPossibleFunctionSignatures.java:25)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotImpl.attrPossibleFunctionSignatures(ExprMemberMethodDotImpl.java:491)
	at de.peeeq.wurstscript.attributes.AttrFunctionSignature.calculate(AttrFunctionSignature.java:16)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotImpl.attrFunctionSignature(ExprMemberMethodDotImpl.java:505)
	at de.peeeq.wurstscript.attributes.AttrExprType.calculate(AttrExprType.java:413)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotImpl.attrTypRaw(ExprMemberMethodDotImpl.java:379)
	at de.peeeq.wurstscript.attributes.AttrExprType.normalizedType(AttrExprType.java:507)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotImpl.attrTyp(ExprMemberMethodDotImpl.java:351)
	at de.peeeq.wurstscript.attributes.PossibleFuncDefs.calculate(PossibleFuncDefs.java:48)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrPossibleFuncDefs(ExprMemberMethodDotDotImpl.java:569)
	at de.peeeq.wurstscript.attributes.AttrPossibleFunctionSignatures.calculate(AttrPossibleFunctionSignatures.java:25)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrPossibleFunctionSignatures(ExprMemberMethodDotDotImpl.java:491)
	at de.peeeq.wurstscript.attributes.AttrFunctionSignature.calculate(AttrFunctionSignature.java:16)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrFunctionSignature(ExprMemberMethodDotDotImpl.java:505)
	at de.peeeq.wurstscript.attributes.AttrExprType.calculate(AttrExprType.java:550)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrTypRaw(ExprMemberMethodDotDotImpl.java:379)
	at de.peeeq.wurstscript.attributes.AttrExprType.normalizedType(AttrExprType.java:507)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrTyp(ExprMemberMethodDotDotImpl.java:351)
	at de.peeeq.wurstscript.attributes.AttrFuncDef.calculate(AttrFuncDef.java:68)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrFuncLink(ExprMemberMethodDotDotImpl.java:583)
	at de.peeeq.wurstscript.attributes.AttrNameDef.tryGetNameDef(AttrNameDef.java:115)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.tryGetNameDef(ExprMemberMethodDotDotImpl.java:482)
	at de.peeeq.wurstio.languageserver.requests.GetUsages.execute(GetUsages.java:61)
	at de.peeeq.wurstio.languageserver.requests.GetUsages.execute(GetUsages.java:18)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	... 4 more

[Error - 21:04:45] Request textDocument/documentHighlight failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: de.peeeq.wurstscript.ast.CyclicDependencyError
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.handleException(UserRequest.java:40)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$handle$3(LanguageWorker.java:272)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:34)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.lang.Thread.run(Unknown Source)
Caused by: de.peeeq.wurstscript.ast.CyclicDependencyError
	at de.peeeq.wurstscript.ast.WEntitiesImpl.attrNameLinks(WEntitiesImpl.java:191)
	at de.peeeq.wurstscript.attributes.names.NameResolution.lookupFuncsNoConfig(NameResolution.java:36)
	at de.peeeq.wurstscript.ast.ExprFunctionCallImpl.lookupFuncsNoConfig(ExprFunctionCallImpl.java:582)
	at de.peeeq.wurstscript.attributes.names.NameResolution.lookupFuncs(NameResolution.java:49)
	at de.peeeq.wurstscript.attributes.names.NameResolution.lookupFuncsShort(NameResolution.java:269)
	at de.peeeq.wurstscript.ast.ExprFunctionCallImpl.lookupFuncs(ExprFunctionCallImpl.java:606)
	at de.peeeq.wurstscript.attributes.PossibleFuncDefs.searchFunction(PossibleFuncDefs.java:87)
	at de.peeeq.wurstscript.attributes.PossibleFuncDefs.calculate(PossibleFuncDefs.java:55)
	at de.peeeq.wurstscript.ast.ExprFunctionCallImpl.attrPossibleFuncDefs(ExprFunctionCallImpl.java:531)
	at de.peeeq.wurstscript.attributes.AttrPossibleFunctionSignatures.calculate(AttrPossibleFunctionSignatures.java:25)
	at de.peeeq.wurstscript.ast.ExprFunctionCallImpl.attrPossibleFunctionSignatures(ExprFunctionCallImpl.java:453)
	at de.peeeq.wurstscript.attributes.AttrFunctionSignature.calculate(AttrFunctionSignature.java:16)
	at de.peeeq.wurstscript.ast.ExprFunctionCallImpl.attrFunctionSignature(ExprFunctionCallImpl.java:467)
	at de.peeeq.wurstscript.attributes.AttrExprType.calculate(AttrExprType.java:413)
	at de.peeeq.wurstscript.ast.ExprFunctionCallImpl.attrTypRaw(ExprFunctionCallImpl.java:341)
	at de.peeeq.wurstscript.attributes.AttrExprType.normalizedType(AttrExprType.java:507)
	at de.peeeq.wurstscript.ast.ExprFunctionCallImpl.attrTyp(ExprFunctionCallImpl.java:313)
	at de.peeeq.wurstscript.attributes.PossibleFuncDefs.calculate(PossibleFuncDefs.java:48)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrPossibleFuncDefs(ExprMemberMethodDotDotImpl.java:569)
	at de.peeeq.wurstscript.attributes.AttrPossibleFunctionSignatures.calculate(AttrPossibleFunctionSignatures.java:25)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrPossibleFunctionSignatures(ExprMemberMethodDotDotImpl.java:491)
	at de.peeeq.wurstscript.attributes.AttrFunctionSignature.calculate(AttrFunctionSignature.java:16)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrFunctionSignature(ExprMemberMethodDotDotImpl.java:505)
	at de.peeeq.wurstscript.attributes.AttrExprType.calculate(AttrExprType.java:550)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrTypRaw(ExprMemberMethodDotDotImpl.java:379)
	at de.peeeq.wurstscript.attributes.AttrExprType.normalizedType(AttrExprType.java:507)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrTyp(ExprMemberMethodDotDotImpl.java:351)
	at de.peeeq.wurstscript.attributes.PossibleFuncDefs.calculate(PossibleFuncDefs.java:48)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotImpl.attrPossibleFuncDefs(ExprMemberMethodDotImpl.java:569)
	at de.peeeq.wurstscript.attributes.AttrPossibleFunctionSignatures.calculate(AttrPossibleFunctionSignatures.java:25)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotImpl.attrPossibleFunctionSignatures(ExprMemberMethodDotImpl.java:491)
	at de.peeeq.wurstscript.attributes.AttrFunctionSignature.calculate(AttrFunctionSignature.java:16)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotImpl.attrFunctionSignature(ExprMemberMethodDotImpl.java:505)
	at de.peeeq.wurstscript.attributes.AttrExprType.calculate(AttrExprType.java:413)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotImpl.attrTypRaw(ExprMemberMethodDotImpl.java:379)
	at de.peeeq.wurstscript.attributes.AttrExprType.normalizedType(AttrExprType.java:507)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotImpl.attrTyp(ExprMemberMethodDotImpl.java:351)
	at de.peeeq.wurstscript.attributes.PossibleFuncDefs.calculate(PossibleFuncDefs.java:48)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrPossibleFuncDefs(ExprMemberMethodDotDotImpl.java:569)
	at de.peeeq.wurstscript.attributes.AttrPossibleFunctionSignatures.calculate(AttrPossibleFunctionSignatures.java:25)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrPossibleFunctionSignatures(ExprMemberMethodDotDotImpl.java:491)
	at de.peeeq.wurstscript.attributes.AttrFunctionSignature.calculate(AttrFunctionSignature.java:16)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrFunctionSignature(ExprMemberMethodDotDotImpl.java:505)
	at de.peeeq.wurstscript.attributes.AttrExprType.calculate(AttrExprType.java:550)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrTypRaw(ExprMemberMethodDotDotImpl.java:379)
	at de.peeeq.wurstscript.attributes.AttrExprType.normalizedType(AttrExprType.java:507)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrTyp(ExprMemberMethodDotDotImpl.java:351)
	at de.peeeq.wurstscript.attributes.AttrFuncDef.calculate(AttrFuncDef.java:68)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrFuncLink(ExprMemberMethodDotDotImpl.java:583)
	at de.peeeq.wurstscript.attributes.AttrNameDef.tryGetNameDef(AttrNameDef.java:115)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.tryGetNameDef(ExprMemberMethodDotDotImpl.java:482)
	at de.peeeq.wurstio.languageserver.requests.GetUsages.execute(GetUsages.java:61)
	at de.peeeq.wurstio.languageserver.requests.GetUsages.execute(GetUsages.java:18)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	... 4 more

Aug 05, 2018 9:04:57 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: de.peeeq.wurstscript.ast.CyclicDependencyError
java.util.concurrent.CompletionException: de.peeeq.wurstscript.ast.CyclicDependencyError
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.handleException(UserRequest.java:40)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$handle$3(LanguageWorker.java:272)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:34)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.lang.Thread.run(Unknown Source)
Caused by: de.peeeq.wurstscript.ast.CyclicDependencyError
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrFuncLink(ExprMemberMethodDotDotImpl.java:586)
	at de.peeeq.wurstscript.attributes.AttrNameDef.tryGetNameDef(AttrNameDef.java:115)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.tryGetNameDef(ExprMemberMethodDotDotImpl.java:482)
	at de.peeeq.wurstio.languageserver.requests.GetUsages.execute(GetUsages.java:61)
	at de.peeeq.wurstio.languageserver.requests.GetUsages.execute(GetUsages.java:18)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	... 4 more

[Error - 21:04:57] Request textDocument/documentHighlight failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: de.peeeq.wurstscript.ast.CyclicDependencyError
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.handleException(UserRequest.java:40)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$handle$3(LanguageWorker.java:272)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:34)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.lang.Thread.run(Unknown Source)
Caused by: de.peeeq.wurstscript.ast.CyclicDependencyError
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.attrFuncLink(ExprMemberMethodDotDotImpl.java:586)
	at de.peeeq.wurstscript.attributes.AttrNameDef.tryGetNameDef(AttrNameDef.java:115)
	at de.peeeq.wurstscript.ast.ExprMemberMethodDotDotImpl.tryGetNameDef(ExprMemberMethodDotDotImpl.java:482)
	at de.peeeq.wurstio.languageserver.requests.GetUsages.execute(GetUsages.java:61)
	at de.peeeq.wurstio.languageserver.requests.GetUsages.execute(GetUsages.java:18)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	... 4 more
```

**Comment by Cokemonkey11** [comment]
I see you're getting more heavily into contributing on the compiler :+1:
