### ISSUE TITLE
CyclicDependencyError

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#710]
```
2018-08-21 20:59:49 [Wurst LanguageWorker] INFO  languageServer - sync contents for C:\Users\Frotty\Documents\GitHub\Castle Siege Deluxe\wurst\round\Round.wurst 
2018-08-21 20:59:49 [Wurst LanguageWorker] INFO  languageServer - oldHash = 1456576893 == 586899056 
2018-08-21 20:59:49 [Wurst LanguageWorker] INFO  languageServer - replace CU C:\Users\Frotty\Documents\GitHub\Castle Siege Deluxe\wurst\round\Round.wurst 
2018-08-21 20:59:49 [Wurst LanguageWorker] INFO  languageServer - update model with C:\Users\Frotty\Documents\GitHub\Castle Siege Deluxe\wurst\round\Round.wurst 
2018-08-21 20:59:49 [Wurst LanguageWorker] INFO  languageServer - found 0 errors in file C:\Users\Frotty\Documents\GitHub\Castle Siege Deluxe\wurst\round\Round.wurst 
2018-08-21 20:59:49 [Wurst LanguageWorker] INFO  languageServer - do typecheck partial of [C:\Users\Frotty\Documents\GitHub\Castle Siege Deluxe\wurst\round\Round.wurst] 
2018-08-21 20:59:49 [Wurst LanguageWorker] INFO  languageServer - Error 
de.peeeq.wurstscript.ast.CyclicDependencyError: null
	at de.peeeq.wurstscript.ast.ExprVarAccessImpl.attrTyp(ExprVarAccessImpl.java:251)
	at de.peeeq.wurstscript.validation.WurstValidator.checkVarRef(WurstValidator.java:1352)
	at de.peeeq.wurstscript.validation.WurstValidator.visit(WurstValidator.java:1316)
	at de.peeeq.wurstscript.validation.WurstValidator.check(WurstValidator.java:260)
	at de.peeeq.wurstscript.validation.WurstValidator.walkTree(WurstValidator.java:208)
	at de.peeeq.wurstscript.validation.WurstValidator.walkTree(WurstValidator.java:211)
	at de.peeeq.wurstscript.validation.WurstValidator.walkTree(WurstValidator.java:211)
	at de.peeeq.wurstscript.validation.WurstValidator.walkTree(WurstValidator.java:211)
	at de.peeeq.wurstscript.validation.WurstValidator.walkTree(WurstValidator.java:211)
	at de.peeeq.wurstscript.validation.WurstValidator.walkTree(WurstValidator.java:211)
	at de.peeeq.wurstscript.validation.WurstValidator.walkTree(WurstValidator.java:211)
	at de.peeeq.wurstscript.validation.WurstValidator.walkTree(WurstValidator.java:211)
	at de.peeeq.wurstscript.validation.WurstValidator.walkTree(WurstValidator.java:211)
	at de.peeeq.wurstscript.validation.WurstValidator.walkTree(WurstValidator.java:211)
	at de.peeeq.wurstscript.validation.WurstValidator.validate(WurstValidator.java:58)
	at de.peeeq.wurstscript.WurstChecker.checkProg(WurstChecker.java:46)
	at de.peeeq.wurstio.WurstCompilerJassImpl.checkProg(WurstCompilerJassImpl.java:347)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.doTypeCheckPartial(ModelManagerImpl.java:555)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.syncCompilationUnitContent(ModelManagerImpl.java:440)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$2(LanguageWorker.java:185)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by peq** [comment]
I think I found one possible problem and fixed it with eefe7064e903592388086f641daed03c2c15440b

If it happens again, stop what you are doing and post the complete source code of the project here ;)
