### ISSUE TITLE
Wurst Run Map failed

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#726]
_From @luciouskami on September 13, 2018 8:6_

```
9�� 13, 2018 4:03:44 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
����: Internal error: java.lang.NullPointerException
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.handleException(UserRequest.java:40)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.handleException(MapRequest.java:63)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$handle$110(LanguageWorker.java:272)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:34)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$108(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at net.moonlightflower.wc3libs.bin.GameExe.fromDir(GameExe.java:158)
	at net.moonlightflower.wc3libs.bin.GameExe.fromDir(GameExe.java:173)
	at de.peeeq.wurstio.utils.W3Utils.parsePatchVersion(W3Utils.java:43)
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:60)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	... 4 more
but  build works fine
```
[languageServer.log](https://github.com/wurstscript/wurst4vscode/files/2378298/languageServer.log)

_Copied from original issue: wurstscript/wurst4vscode#42_

**Comment by Frotty** [comment]
Because build doesn't require a game executable, which can't be found on your system.

Also doesn't belong in this repo...

**Comment by luciouskami** [comment]
> Because build doesn't require a game executable, which can't be found on your system.

oh,I see. Because of the CN agent Netease,Chinese players almost use war3 ver1.27a.The game executable named "war3.exe",I guess wurst attempted to find "Warcraft III.exe",but it's not existed.
So is there any solution to support the outdated war3 version?
--


.

**Comment by Frotty** [comment]
1.27 is supported, but there was a bug. Should work again now.

**Comment by luciouskami** [comment]
Thank you
