### ISSUE TITLE
language client error

### ISSUE THREAD

**Issue by cloudfox2** [wurstscript/WurstScript#730]
it seems that it caused by my reinstalled java

Log:
initializing workspace
initialization done!
[Error - 11:45:31 PM] Server initialization failed.
Error: command 'wurst.startmap' already exists
	at e.registerCommand (e:\S\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:725:618)
	at Object.registerCommand (e:\S\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:799:950)
	at ExecuteCommandFeature.register (C:\Users\H\.vscode\extensions\peterzeller.wurst-0.2.0\node_modules\vscode-languageclient\lib\client.js:1501:53)
	at ExecuteCommandFeature.initialize (C:\Users\H\.vscode\extensions\peterzeller.wurst-0.2.0\node_modules\vscode-languageclient\lib\client.js:1491:14)
	at LanguageClient.initializeFeatures (C:\Users\H\.vscode\extensions\peterzeller.wurst-0.2.0\node_modules\vscode-languageclient\lib\client.js:2168:21)
	at connection.initialize.then (C:\Users\H\.vscode\extensions\peterzeller.wurst-0.2.0\node_modules\vscode-languageclient\lib\client.js:1888:18)
	at <anonymous>

**Comment by Frotty** [comment]
@cloudfox2 I don't think it makes sense to close this issue if only a strange workaround fixed it?
We would like to solve this problem for anyone encountering this issue and I'm pretty sure those lines serve a purpose.

Also once we update the plugin, you won't be able to use wurst or have to do it again.
