### ISSUE TITLE
urgent: cant build

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/WurstScript#758]
the `compiler.log`
```
2018-11-09 04:40:16 [Wurst LanguageWorker] DEBUG s.crigges.jmpq3.AttributesFile - parsed attributes 
2018-11-09 04:40:16 [Wurst LanguageWorker] DEBUG systems.crigges.jmpq3.JMpqEditor - closed readonly mpq. 
2018-11-09 04:40:24 [Wurst LanguageWorker] WARN  systems.crigges.jmpq3.JMpqEditor - mpq's listfile is incomplete, switching to readonly. 
```
then the plugin tell me : java.nio.channels.NonWritableChannelException

```
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.nio.channels.NonWritableChannelException
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.handleException(UserRequest.java:40)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.handleException(MapRequest.java:58)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$handle$150(LanguageWorker.java:272)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:34)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$148(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.nio.channels.NonWritableChannelException
	at de.peeeq.wurstio.languageserver.requests.MapRequest.compileMap(MapRequest.java:162)
	at de.peeeq.wurstio.languageserver.requests.BuildMap.compileScript(BuildMap.java:171)
	at de.peeeq.wurstio.languageserver.requests.BuildMap.execute(BuildMap.java:79)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	... 4 more
Caused by: java.nio.channels.NonWritableChannelException
	at de.peeeq.wurstio.languageserver.requests.MapRequest.compileMap(MapRequest.java:110)
	... 7 more
```

**Comment by PhoenixZeng** [comment]
i update the compile and stdlib 1 hour ago.

**Comment by PhoenixZeng** [comment]
`mpq's listfile is incomplete`
i dont know why. i use the `ydwe`
before i update  the compiler ,i can build

**Comment by Frotty** [comment]
post the map or an example map with the same behavior. the error means that there are unnamed blocks.

**Comment by PhoenixZeng** [comment]
Nothing special. just a empty project with the default map (save once by ydwe1.32.11)
https://github.com/PhoenixZeng/wurstError
@Frotty

**Comment by Frotty** [comment]
ydwe generates (signature) file i think. maybe you can turn it off.

**Comment by PhoenixZeng** [comment]
I dont know about that. the ydweconfig dont have it. so i dont know how to turn it off.
the older compiler dont have this question.i think the reason is the `mpq's listfile is incomplete, switching to readonly. `
If you don't think that's a problem, I'll have to force the old version of the compiler. Because my map uses a lot of ydwe features. Maybe the generated files you're talking about are related to these features.

**Comment by Frotty** [comment]
I already pushed a fix, read the ticket.

**Comment by PhoenixZeng** [comment]
wow.
so fast. thanks. 
what is you jenkins web-site(i forget it). i cant down it by the setup now

**Comment by Frotty** [comment]
Btw. This is a YDWE issue **again**.
iirc they use stormlib, and then are not using the `compact` command, thus creating empty space in the resulting mpq.
I made a ticket here https://github.com/actboy168/YDWE/issues/158
