### ISSUE TITLE
CompileError: cyclic dependency between functions

### ISSUE THREAD

**Issue by ProButLaggs** [wurstscript/WurstScript#759]
Would it be possible to add an argument that disables checking of cyclic dependency between functions?

**Comment by Frotty** [comment]
Why?

**Comment by ProButLaggs** [comment]
Hello, sorry for short description.

This is log from the Language Server, I will explain what it does.

```
2018-11-13 09:54:06 [Wurst LanguageWorker] INFO  languageServer - Error 
de.peeeq.wurstscript.attributes.CompileError: cyclic dependency between functions: 
 - function addStat  ( C:\projects-wc\Deadlands\wurst\Systems\UnitSystem\Character.wurst line  71)
 - function onChange  ( C:\projects-wc\Deadlands\wurst\Systems\StatSystem\Stat.wurst line  52)
 - function execute  ( C:\projects-wc\Deadlands\wurst\Systems\StatSystem\Stat.wurst line  9)
 - exprclosure   ( C:\projects-wc\Deadlands\wurst\Systems\SpellSystem\SpellTypes\Spell.wurst line  31)
 - function spellLevelChanged  ( C:\projects-wc\Deadlands\wurst\Systems\UnitSystem\Character.wurst line  325)
	at de.peeeq.wurstscript.translation.imtojass.ImToJassTranslator.translateFunctionTransitive(ImToJassTranslator.java:83)
	at de.peeeq.wurstscript.translation.imtojass.ImToJassTranslator.translateFunctionTransitive(ImToJassTranslator.java:90)
	at de.peeeq.wurstscript.translation.imtojass.ImToJassTranslator.translateFunctionTransitive(ImToJassTranslator.java:90)
	at de.peeeq.wurstscript.translation.imtojass.ImToJassTranslator.translateFunctionTransitive(ImToJassTranslator.java:90)
	at de.peeeq.wurstscript.translation.imtojass.ImToJassTranslator.translateFunctionTransitive(ImToJassTranslator.java:90)
	at de.peeeq.wurstscript.translation.imtojass.ImToJassTranslator.translateFunctionTransitive(ImToJassTranslator.java:90)
	at de.peeeq.wurstscript.translation.imtojass.ImToJassTranslator.translateFunctionTransitive(ImToJassTranslator.java:90)
	at de.peeeq.wurstscript.translation.imtojass.ImToJassTranslator.translateFunctionTransitive(ImToJassTranslator.java:90)
	at de.peeeq.wurstscript.translation.imtojass.ImToJassTranslator.translateFunctionTransitive(ImToJassTranslator.java:90)
	at de.peeeq.wurstscript.translation.imtojass.ImToJassTranslator.translateFunctionTransitive(ImToJassTranslator.java:90)
	at de.peeeq.wurstscript.translation.imtojass.ImToJassTranslator.translateFunctionTransitive(ImToJassTranslator.java:90)
	at de.peeeq.wurstscript.translation.imtojass.ImToJassTranslator.translate(ImToJassTranslator.java:50)
	at de.peeeq.wurstio.WurstCompilerJassImpl.transformProgToJass(WurstCompilerJassImpl.java:493)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.compileMap(MapRequest.java:134)
	at de.peeeq.wurstio.languageserver.requests.BuildMap.compileScript(BuildMap.java:171)
	at de.peeeq.wurstio.languageserver.requests.BuildMap.execute(BuildMap.java:79)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$148(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.lang.Thread.run(Unknown Source)
```

- Character class has function addStat(Stat stat, real value) which increases target stat of unit, and triggers stat.onChange
- Stat class has function onChange(Character char, real value) which updates stat (visualy) and triggers updating of other stats (Like 'All Stats' Stat increases 'Strength')
- Stat class has closure with execute function that is triggered when stat is changed. This acts as 'event' when stat changes.
- There is SpellLevel stat, which has closure that updates level of the Spell Class.
- Spell has list of stats that are increased when spell level is changed (like damage of spell, etc...).
- When SpellLevel stat is changed it triggers Character.spellLevelChanged() that goes throue stats of Spell and calls addStat() which makes it cylic dependent?

Also cyclic dependency for functions is not detecting 100% of the time. When I get error I just re run compiling and it sometimes work.

**Comment by Frotty** [comment]
If it only happens some times, it's simply a bug in the compiler.
Wurst resolves all cyclic dependencies by merging those functions into one with if dispatch to the singular function bodies. You can see this in the emitted Jass.
Looks like in some cases the cycle removal doesn't work. @peq recently changed something there, so that might be the issue.
The most important thing here would be the code to reproduce the problem I believe.

**Comment by ProButLaggs** [comment]
I could give you whole repo but it is too large (around 5000 lines).
I will upload smaller example that can be reproduced soon.

**Comment by peq** [comment]
Small examples are nice, but the whole repo would also allow us to find the problem quickly.

**Comment by peq** [comment]
@ProButLaggs  any chance you can share the code that triggers this bug?

**Comment by Frotty** [comment]
@ProButLaggs Any updates on this?

**Comment by WareditorGit** [comment]
I have a repo with what I think is the same issue.
The following, line make it so the compilation will fail at the end of it (after all the stages).
https://github.com/WareditorGit/Stranniki/blob/52e7fd75e99337e481823b18be7bf9b246f1ba86/wurst/___systems/entity/_core/Entity.wurst#L87

**Comment by peq** [comment]
Thanks for the code @WareditorGit 

It was a very interesting bug: I implemented the algorithm from https://en.wikipedia.org/wiki/Path-based_strong_component_algorithm for detecting strongly connected components and got the following line wrong:

> Repeatedly pop vertices from P until the top element of P has a preorder number less than or equal to the preorder number of w.

I interpreted this as a do-while loop instead of a while loop, because the action came before the condition in the description.
