### ISSUE TITLE
Cyclic dependency error

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#779]
probably related to #759

```
Caused by: de.peeeq.wurstscript.ast.CyclicDependencyError
	at de.peeeq.wurstscript.ast.ExprClosureImpl.attrExpectedTyp(ExprClosureImpl.java:302)
	at de.peeeq.wurstscript.attributes.AttrVarDefType.calculate(AttrVarDefType.java:44)
	at de.peeeq.wurstscript.ast.WShortParameterImpl.attrTyp(WShortParameterImpl.java:187)
	at de.peeeq.wurstscript.attributes.AttrExprType.calculate(AttrExprType.java:515)
	at de.peeeq.wurstscript.ast.ExprClosureImpl.attrTypRaw(ExprClosureImpl.java:260)
	at de.peeeq.wurstscript.attributes.AttrExprType.normalizedType(AttrExprType.java:507)
	at de.peeeq.wurstscript.ast.ExprClosureImpl.attrTyp(ExprClosureImpl.java:224)
	at de.peeeq.wurstscript.attributes.AttrExprExpectedType.calculate(AttrExprExpectedType.java:47)
	at de.peeeq.wurstscript.ast.ExprClosureImpl.attrExpectedTypRaw(ExprClosureImpl.java:278)
	at de.peeeq.wurstscript.attributes.AttrExprExpectedType.normalizedType(AttrExprExpectedType.java:159)
	at de.peeeq.wurstscript.ast.ExprClosureImpl.attrExpectedTyp(ExprClosureImpl.java:296)
	at de.peeeq.wurstio.languageserver.requests.GetCompletions.computeCompletionProposals(GetCompletions.java:116)
	at de.peeeq.wurstio.languageserver.requests.GetCompletions.execute(GetCompletions.java:76)
	at de.peeeq.wurstio.languageserver.requests.GetCompletions.execute(GetCompletions.java:33)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	... 4 more
```
I couldnt get a small example easily, so here is a step by step guide:

1. open stdlib project
2. add the code
```

function take<T>(int numElems, LinkedList<T> list) returns LinkedList<T>
    return list.take(numElems)

interface TakeNumElems<T>
    function call(LinkedList<T> list) returns LinkedList<T>

function take<T>(int numElems) returns TakeNumElems<T>
    return list -> take<int>(numElems, list)

@Test
function testTake2()
    let ints = asList(1, 2, 3)
    let take2 = take(2)
    take2.call<int>(ints)
```

3. go to the line `return list -> take<int>(numElems, list)` and write `<s` after `return list`.
The incomplete generic param triggers the error.

**Comment by peq** [comment]
This is a different problem. In #759 it happens while compiling the code, here it is while type checking. .
