### ISSUE TITLE
do not report error when open the git change file

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/WurstScript#795]
```
���� 04, 2019 12:50:13 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
����: Internal error: java.lang.RuntimeException: URI git:/c%3A/Users/Phoenix/Documents/Legend_of_chusen/wurst/lib/system/Bullet.wurst?%7B%22path%22%3A%22c%3A%5C%5CUsers%5C%5CPhoenix%5C%5CDocuments%5C%5CLegend_of_chusen%5C%5Cwurst%5C%5Clib%5C%5Csystem%5C%5CBullet.wurst%22%2C%22ref%22%3A%22~%22%7D is not a vald file
java.util.concurrent.CompletionException: java.lang.RuntimeException: URI git:/c%3A/Users/Phoenix/Documents/Legend_of_chusen/wurst/lib/system/Bullet.wurst?%7B%22path%22%3A%22c%3A%5C%5CUsers%5C%5CPhoenix%5C%5CDocuments%5C%5CLegend_of_chusen%5C%5Cwurst%5C%5Clib%5C%5Csystem%5C%5CBullet.wurst%22%2C%22ref%22%3A%22~%22%7D is not a vald file
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.handleException(UserRequest.java:40)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$handle$3(LanguageWorker.java:272)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:34)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: URI git:/c%3A/Users/Phoenix/Documents/Legend_of_chusen/wurst/lib/system/Bullet.wurst?%7B%22path%22%3A%22c%3A%5C%5CUsers%5C%5CPhoenix%5C%5CDocuments%5C%5CLegend_of_chusen%5C%5Cwurst%5C%5Clib%5C%5Csystem%5C%5CBullet.wurst%22%2C%22ref%22%3A%22~%22%7D is not a vald file
	at de.peeeq.wurstio.languageserver.WFile.create(WFile.java:40)
	at de.peeeq.wurstio.languageserver.WFile.create(WFile.java:48)
	at de.peeeq.wurstio.languageserver.WFile.create(WFile.java:62)
	at de.peeeq.wurstio.languageserver.requests.Colors$DocumentColorRequest.execute(Colors.java:37)
	at de.peeeq.wurstio.languageserver.requests.Colors$DocumentColorRequest.execute(Colors.java:26)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	... 4 more
Caused by: java.lang.IllegalArgumentException: URI scheme is not "file"
	at java.io.File.<init>(File.java:421)
	at de.peeeq.wurstio.languageserver.WFile.create(WFile.java:38)
	... 9 more

[Error - 12:50:13 AM] Request textDocument/colorPresentation failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.RuntimeException: URI git:/c%3A/Users/Phoenix/Documents/Legend_of_chusen/wurst/lib/system/Bullet.wurst?%7B%22path%22%3A%22c%3A%5C%5CUsers%5C%5CPhoenix%5C%5CDocuments%5C%5CLegend_of_chusen%5C%5Cwurst%5C%5Clib%5C%5Csystem%5C%5CBullet.wurst%22%2C%22ref%22%3A%22~%22%7D is not a vald file
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.handleException(UserRequest.java:40)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$handle$3(LanguageWorker.java:272)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:34)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: URI git:/c%3A/Users/Phoenix/Documents/Legend_of_chusen/wurst/lib/system/Bullet.wurst?%7B%22path%22%3A%22c%3A%5C%5CUsers%5C%5CPhoenix%5C%5CDocuments%5C%5CLegend_of_chusen%5C%5Cwurst%5C%5Clib%5C%5Csystem%5C%5CBullet.wurst%22%2C%22ref%22%3A%22~%22%7D is not a vald file
	at de.peeeq.wurstio.languageserver.WFile.create(WFile.java:40)
	at de.peeeq.wurstio.languageserver.WFile.create(WFile.java:48)
	at de.peeeq.wurstio.languageserver.WFile.create(WFile.java:62)
	at de.peeeq.wurstio.languageserver.requests.Colors$DocumentColorRequest.execute(Colors.java:37)
	at de.peeeq.wurstio.languageserver.requests.Colors$DocumentColorRequest.execute(Colors.java:26)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	... 4 more
Caused by: java.lang.IllegalArgumentException: URI scheme is not "file"
	at java.io.File.<init>(File.java:421)
	at de.peeeq.wurstio.languageserver.WFile.create(WFile.java:38)
	... 9 more


```

**Comment by PhoenixZeng** [comment]
![qq 20190204005258](https://user-images.githubusercontent.com/26225903/52179577-3c261b80-2817-11e9-84d3-cb462db4624a.jpg)
