### ISSUE TITLE
"not implemented" Error when running tests on code that has errors

### ISSUE THREAD

**Issue by Robbepop** [wurstscript/WurstScript#808]
When using `@compiletime` and calling `R2W(1116.0, 2, 2)` the WurstScript interpreter crashes with an internal error.

Note that in my experiments the call to `R2W` is not direct but through `real.toString`.
Also other `precision` params such as `0` or `1` result in the same internal error.

**Comment by Frotty** [comment]
It is simply not yet implemented for compiletime.
But for some reason the actual exception that should say that, gets hidden by this one:
```
java.lang.Error: not implemented
	at de.peeeq.wurstscript.types.WurstTypeUnknown.imTranslateType(WurstTypeUnknown.java:52)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.getVarFor(ImTranslator.java:941)
	at de.peeeq.wurstscript.translation.imtranslation.StmtTranslation.translate(StmtTranslation.java:34)
	at de.peeeq.wurstscript.ast.LocalVarDefImpl.imTranslateStmt(LocalVarDefImpl.java:482)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.translateStatements(ImTranslator.java:988)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:88)
	at de.peeeq.wurstscript.ast.FuncDefImpl.imTranslateEntity(FuncDefImpl.java:635)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:61)
	at de.peeeq.wurstscript.ast.WPackageImpl.imTranslateTLD(WPackageImpl.java:438)
	at de.peeeq.wurstscript.translation.imtranslation.TLDTranslation.translate(TLDTranslation.java:54)
	at de.peeeq.wurstscript.ast.WPackageImpl.imTranslateTLD(WPackageImpl.java:438)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.translateCompilationUnit(ImTranslator.java:315)
	at de.peeeq.wurstscript.translation.imtranslation.ImTranslator.translateProg(ImTranslator.java:124)
	at de.peeeq.wurstio.languageserver.requests.RunTests.translateProg(RunTests.java:278)
	at de.peeeq.wurstio.languageserver.requests.RunTests.execute(RunTests.java:101)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:171)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:29)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:146)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Frotty** [comment]
Oh wait, `R2W` does not exist. `R2SW` is what you're looking for, which does seem to work.
You should add a test that replicates the error.

**Comment by Robbepop** [comment]
As far as I explored it happens only when the `real` value is above a certain threshold. Like above 1000.
So `R2SW(1.0, 2, 2)` runs fine however, `R2SW(1116.0, 2, 2)` crashes. Please take this note with a big grain of salt.

**Comment by peq** [comment]
Thanks for the report, @Robbepop . Glad to see you using Wurst :)

The problem was that Java added a separator for the thousands, so big values would be converted to `1,116.00` and then the old code tried to read that into a float again, which was not really necessary.

**Comment by Robbepop** [comment]
Thank you for creating WurstScript! I very much enjoy using it!
Aaaand thanks for the bug fix. :)
