### ISSUE TITLE
could not find a war3 installation

### ISSUE THREAD

**Issue by HodenX** [wurstscript/WurstScript#880]
Hi,
When i run wurst map,it cause below issue:
logfile:
Loading Wurst version 1.8.1.0-jenkins-Wurst-1185
initialization done!
net.moonlightflower.wc3libs.port.NotFoundException: java.lang.Exception: tried: [Warcraft III.exe, Frozen Throne.exe, war3.exe, x86\Warcraft III.exe, x86_64\Warcraft III.exe]
	at net.moonlightflower.wc3libs.port.StdGameExeFinder.fromDirIgnoreVersion(StdGameExeFinder.java:91)
	at net.moonlightflower.wc3libs.port.StdGameExeFinder.fromDirIgnoreVersion(StdGameExeFinder.java:96)
	at de.peeeq.wurstio.utils.W3Utils.parsePatchVersion(W3Utils.java:49)
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:77)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:171)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:29)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:146)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Exception: tried: [Warcraft III.exe, Frozen Throne.exe, war3.exe, x86\Warcraft III.exe, x86_64\Warcraft III.exe]
	... 9 more

**Comment by CinderellaM** [comment]
build map error
------------------------------------------------
���� 27, 2019 7:45:58 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
����: Internal error: java.lang.RuntimeException: java.lang.NullPointerException
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.handleException(UserRequest.java:40)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.handleException(MapRequest.java:79)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$handle$3(LanguageWorker.java:277)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:34)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:171)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:29)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:146)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at de.peeeq.wurstio.languageserver.ProjectConfigBuilder.apply(ProjectConfigBuilder.java:82)
	at de.peeeq.wurstio.languageserver.requests.BuildMap.execute(BuildMap.java:60)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	... 4 more
Caused by: java.lang.NullPointerException
	at java.io.FileInputStream.<init>(Unknown Source)
	at de.peeeq.wurstio.languageserver.ProjectConfigBuilder.apply(ProjectConfigBuilder.java:40)
	... 6 more

**Comment by Frotty** [comment]
- Where is your waracraft installation?
- What did you configure in settings.json?
- Those problems are unrelated, make separate tickets

**Comment by CinderellaM** [comment]
1.Where is your waracraft installation?
--->I have war3 of 2 version:1.27 and 1.31.I use 1.27 (D:\\Warcraft III Frozen Throne\\)
2.What did you configure in settings.json?
---->
{
    "wurst.wurstJar": "C:\\Users\\51356\\.wurst\\wurstscript.jar",
    "wurst.javaOpts": ["-XX:+UseG1GC", "-XX:+UseStringDeduplication", "-XX:+AggressiveOpts", "-Xmx1G"],
    "wurst.wc3path": "D:\\Warcraft III Frozen Throne\\",
	"files.associations": {
        "wurst.build": "yaml"
    },
	"search.useIgnoreFiles": false
}
3.Those are not complete logs?
---->how to find a complete logs?

**Comment by CinderellaM** [comment]
In addition, 
f1-->run map  dont present any error message without lunching war3
f1--->build your map via build.wurst create the crash log above and  build process block in running PJASS

**Comment by Frotty** [comment]
As the issue templates states, logs are in `~/.wurst/logs`. Paste compiler and languageServer logs somewhere.

How did you configure your gamepath?
```
"wurst.wc3path": "D:\Warcraft III Frozen Throne\",
```
This is invalid json, the backslashes must be escaped (`\\`). 

Your wc3 dir and wurst jar being on different partitions might be a problem.

**Comment by HodenX** [comment]
hi,Frotty
I have found out the issue that I forget to add PATH environment variable.
Now I can lunch the war3 through run map command ,but It don`t start my test map automatically when I use the war3 of 1.27

I use 1.31 to try again, it fails with error "Cannot run program xxx/pjassxxxexe:CreateProcess error=1450"

**Comment by Frotty** [comment]
> I have found out the issue that I forget to add PATH environment variable.

PATH has nothing to do with launching wc3.

> I use 1.31 to try again, it fails with error "Cannot run program xxx/pjassxxxexe:CreateProcess error=1450"

Still waiting for logs.

**Comment by Frotty** [comment]
Hi, do you still want to fix this?
Please paste the logs from `~/.wurst/logs` and check if there is anything in the vscode output tab (CTRL + SHIFT + U, then select wurstLangServer).

Otherwise I will close.
