### ISSUE TITLE
compiletime(real) bug

### ISSUE THREAD

**Issue by anufis** [wurstscript/WurstScript#881]
Code:

```
package Test

init
    let q = compiletime(1.5)
    print(q)
```

Error:

```
Loading Wurst version 1.8.1.0-jenkins-Wurst-1186
initialization done!
��� 30, 2019 5:40:25 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.RuntimeException: de.peeeq.wurstio.languageserver.requests.RequestFailedException: Could not compile project (error in running compiletime functions/expressions): 
Error in File Test.wurst line 4:
 Compiletime expression returned unsupported value 1.5
  at H:\Games\Warcraft III\Programms\WurstTest\wurst\Test.wurst line 4
java.util.concurrent.CompletionException: java.lang.RuntimeException: de.peeeq.wurstio.languageserver.requests.RequestFailedException: Could not compile project (error in running compiletime functions/expressions): 
Error in File Test.wurst line 4:
 Compiletime expression returned unsupported value 1.5
  at H:\Games\Warcraft III\Programms\WurstTest\wurst\Test.wurst line 4
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.handleException(UserRequest.java:40)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.handleException(MapRequest.java:79)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$handle$3(LanguageWorker.java:277)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:34)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:171)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:29)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:146)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: de.peeeq.wurstio.languageserver.requests.RequestFailedException: Could not compile project (error in running compiletime functions/expressions): 
Error in File Test.wurst line 4:
 Compiletime expression returned unsupported value 1.5
  at H:\Games\Warcraft III\Programms\WurstTest\wurst\Test.wurst line 4
	at de.peeeq.wurstio.languageserver.requests.MapRequest.compileMap(MapRequest.java:220)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.compileScript(MapRequest.java:340)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.compileScript(MapRequest.java:355)
	at de.peeeq.wurstio.languageserver.requests.BuildMap.execute(BuildMap.java:57)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	... 4 more
Caused by: de.peeeq.wurstio.languageserver.requests.RequestFailedException: Could not compile project (error in running compiletime functions/expressions): 
Error in File Test.wurst line 4:
 Compiletime expression returned unsupported value 1.5
  at H:\Games\Warcraft III\Programms\WurstTest\wurst\Test.wurst line 4
	at de.peeeq.wurstio.WurstCompilerJassImpl.runCompiletime(WurstCompilerJassImpl.java:116)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.compileMap(MapRequest.java:163)
	... 8 more
Caused by: Error in File Test.wurst line 4:
 Compiletime expression returned unsupported value 1.5
  at H:\Games\Warcraft III\Programms\WurstTest\wurst\Test.wurst line 4
	at de.peeeq.wurstio.CompiletimeFunctionRunner.sendErrors(CompiletimeFunctionRunner.java:143)
	at de.peeeq.wurstio.CompiletimeFunctionRunner.run(CompiletimeFunctionRunner.java:113)
	at de.peeeq.wurstio.WurstCompilerJassImpl.runCompiletime(WurstCompilerJassImpl.java:110)
	... 9 more
Caused by: Compiletime expression returned unsupported value 1.5
  at H:\Games\Warcraft III\Programms\WurstTest\wurst\Test.wurst line 4
Stack trace:
at : Test.wurst, line 4
... when executing compiletime expression  in Test.wurst:4

	at de.peeeq.wurstio.CompiletimeFunctionRunner.constantToExpr(CompiletimeFunctionRunner.java:310)
	at de.peeeq.wurstio.CompiletimeFunctionRunner.executeCompiletimeExpr(CompiletimeFunctionRunner.java:217)
	at de.peeeq.wurstio.CompiletimeFunctionRunner.execute(CompiletimeFunctionRunner.java:164)
	at de.peeeq.wurstio.CompiletimeFunctionRunner.run(CompiletimeFunctionRunner.java:103)
	... 10 more

```

[Screenshot](https://puu.sh/DZbCH/b84be8b9f7.png)

**Comment by Frotty** [comment]
reals were not implemented yet 🤷‍♂
