### ISSUE TITLE
when i use vscode compile my map,it can not work

### ISSUE THREAD

**Issue by HarounGY** [wurstscript/WurstScript#891]
the project build by WurstSetup.jar,  just print("Hello World")

logs:

2019-08-29 15:34:24 [Wurst LanguageWorker] INFO  languageServer - found 0 errors in file H:\newBegin\test\MyWurstProject\_build\dependencies\wurstStdlib2\wurst\_wurst\TypeCasting.wurst 
2019-08-29 15:34:27 [Wurst LanguageWorker] INFO  languageServer - debug - finished checkProg 
2019-08-29 15:34:27 [Wurst LanguageWorker] INFO  languageServer - finished typechecking in 2222ms 
2019-08-29 15:34:27 [Wurst LanguageWorker] INFO  languageServer - Finished building H:\newBegin\test\MyWurstProject 
2019-08-29 15:34:27 [Wurst LanguageWorker] INFO  languageServer - oldHash = 1794185151 == 1794185151 
2019-08-29 15:34:27 [Wurst LanguageWorker] INFO  languageServer - CU H:\newBegin\test\MyWurstProject\wurst\Hello.wurst was unchanged. 
2019-08-29 15:34:27 [Wurst LanguageWorker] INFO  languageServer - Execute RunMap, 
wc3Path =H:\war3Version\1.31ptr\War3_1.31.0.11889\x86_64,
 map = h:\newBegin\test\MyWurstProject\ExampleMap.w3x,
 compileArgs = [-runcompiletimefunctions, -injectobjects, -stacktraces],
 workspaceRoot = H:\newBegin\test\MyWurstProject,
 runArgs = [-runcompiletimefunctions, -injectobjects, -stacktraces] 
2019-08-29 15:34:27 [Wurst LanguageWorker] ERROR languageServer - Error 
java.lang.NoClassDefFoundError: config/WurstProjectConfig
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:67)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:171)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:29)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:146)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: config.WurstProjectConfig
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 6 common frames omitted

**Comment by Frotty** [comment]
Just tried a fresh install and can't reproduce this.
Did you modify files inside your `~/.wurst` folder ?
You can try deleting the `~/.wurst` folder and reinstalling wurst.

**Comment by HarounGY** [comment]
ok i will try

**Comment by Frotty** [comment]
Any update on the situation?

**Comment by HarounGY** [comment]
I'm in China. I failed when I updated the new version because of the net. 
i try reinstalling wurst. it works now.
thank you 。

**Comment by Frotty** [comment]
So fixed? Is there still anything to do here?

**Comment by HarounGY** [comment]
thank you，nothing。
