### ISSUE TITLE
Java Null Pointer Exception with Wurst Unit Tests

### ISSUE THREAD

**Issue by maltebp** [wurstscript/WurstScript#915]
I just updated to compiler build 1223, and now I can't seem to run any Wurst unit tests within Visual Studio Code. Every time I do, I get this error in the _wurstLanguageServer_ output window:

```Running unit tests..

java.lang.NullPointerException
	at de.peeeq.wurstio.CompiletimeFunctionRunner.getCompiletimeStateInitFunction(CompiletimeFunctionRunner.java:325)
	at de.peeeq.wurstio.CompiletimeFunctionRunner.addCompiletimeStateInitAlloc(CompiletimeFunctionRunner.java:349)
	at de.peeeq.wurstio.CompiletimeFunctionRunner.access$200(CompiletimeFunctionRunner.java:39)
	at de.peeeq.wurstio.CompiletimeFunctionRunner$3.initFor(CompiletimeFunctionRunner.java:277)
	at de.peeeq.wurstio.CompiletimeFunctionRunner$3.initFor(CompiletimeFunctionRunner.java:260)
	at de.peeeq.wurstscript.translation.imtranslation.GetAForB.getFor(GetAForB.java:17)
	at de.peeeq.wurstio.CompiletimeFunctionRunner.constantToExpr(CompiletimeFunctionRunner.java:305)
	at de.peeeq.wurstio.CompiletimeFunctionRunner.executeCompiletimeExpr(CompiletimeFunctionRunner.java:217)
	at de.peeeq.wurstio.CompiletimeFunctionRunner.execute(CompiletimeFunctionRunner.java:164)
	at de.peeeq.wurstio.CompiletimeFunctionRunner.run(CompiletimeFunctionRunner.java:103)
	at de.peeeq.wurstio.languageserver.requests.RunTests.runTests(RunTests.java:156)
	at de.peeeq.wurstio.languageserver.requests.RunTests.execute(RunTests.java:115)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:171)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:29)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:146)
	at java.base/java.lang.Thread.run(Unknown Source)
Error in File ErrorHandling.wurst line 15:
 null
Error in File ErrorHandling.wurst line 15:
 ... when executing compiletime expression  in ErrorHandling.wurst:15
There were some problem while running compiletime expressions and functions.
```

I tested this with a newly created project, where I created 'Test.wurst': 

```
package Test

import Wurstunit

@Test
public function test()
    assertTrue(true)
```

and ran the unit tests.

**Comment by peq** [comment]
The error does not occur with the Test.wurst file alone. Can you please share the whole project? The error seems to occur in combination with using handles in a compiletime expression.

I pushed a quick fix that might fix the problem.

**Comment by maltebp** [comment]
That file is all the Wurst files in the project, but I'll upload it here anyways. It's with build version 1223 (before updating). Tried to update to the newest (1226), but didn't change the problem.
[UnitTestProject.zip](https://github.com/wurstscript/WurstScript/files/4018984/UnitTestProject.zip)

I first stumpled on the problem in another project where I did indeed, attempted to use handles in compiletime, realizing that wasn't right. Thought that was the problem, but it persisted after removing it.

Anyways, here are my logs as well (not sure if they're useful)
[languageServer.log](https://github.com/wurstscript/WurstScript/files/4018989/languageServer.log)
[setup.log](https://github.com/wurstscript/WurstScript/files/4018990/setup.log)
[compiler.log](https://github.com/wurstscript/WurstScript/files/4018991/compiler.log)

**Comment by peq** [comment]
Thanks. Turns out I just had an old version of StdLib when testing.

Should be fixed with build 1231.

**Comment by maltebp** [comment]
Cheers, that seemed to fix it, yeah.

Thanks for the help
