### ISSUE TITLE
[Reforged] java.lang.RuntimeException unknown format 31

### ISSUE THREAD

**Issue by jlfarris91** [wurstscript/WurstScript#933]
This error occurs every time I build my map in VSCode in the Reforged environment. Looks like Blizzard has changed the w3i file format for Reforged.

```
java.lang.RuntimeException: 
unknown format 31
supported formats:
-1
28
25
18
	at de.peeeq.wurstio.languageserver.ProjectConfigBuilder.apply(ProjectConfigBuilder.java:83)
	at de.peeeq.wurstio.languageserver.requests.BuildMap.execute(BuildMap.java:65)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:171)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:29)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:146)
	at java.lang.Thread.run(Unknown Source)
Caused by: net.moonlightflower.wc3libs.bin.BinStream$StreamException: null
	at net.moonlightflower.wc3libs.bin.Wc3BinInputStream.getFormat(Wc3BinInputStream.java:428)
	at net.moonlightflower.wc3libs.bin.app.W3I.read_auto(W3I.java:2552)
	at net.moonlightflower.wc3libs.bin.app.W3I.read(W3I.java:2558)
	at net.moonlightflower.wc3libs.bin.app.W3I.read(W3I.java:2601)
	at net.moonlightflower.wc3libs.bin.app.W3I.<init>(W3I.java:2625)
	at de.peeeq.wurstio.languageserver.ProjectConfigBuilder.prepareW3I(ProjectConfigBuilder.java:91)
	at de.peeeq.wurstio.languageserver.ProjectConfigBuilder.apply(ProjectConfigBuilder.java:40)
	... 6 common frames omitted
```

[languageServer.log](https://pastebin.com/m85Dg9Hn)
[compiler.log](https://pastebin.com/THdi61bP)

**Comment by peq** [comment]
Are you using the latest version of Wurst? 

(You can use the Wurst Setup Tool to update and show the compiler build number, should be 1241 now)

**Comment by jlfarris91** [comment]
I was not. I apologize - I thought using `grill install` was enough to update wurst. Disregard this bug.

**Comment by Frotty** [comment]
`grill install` updates the project, like `npm install` `pod install` and all the other package manager installs.
