### ISSUE TITLE
Cannot build map after latest War 3 update

### ISSUE THREAD

**Issue by jlfarris91** [wurstscript/WurstScript#948]
```
net.moonlightflower.wc3libs.port.NotFoundException: java.lang.Exception: tried: [Warcraft III.exe, Frozen Throne.exe, war3.exe, x86\Warcraft III.exe, x86_64\Warcraft III.exe]
	at net.moonlightflower.wc3libs.port.win.WinGameExeFinder.fromDirIgnoreVersion(WinGameExeFinder.java:101)
	at net.moonlightflower.wc3libs.port.win.WinGameExeFinder.fromDirIgnoreVersion(WinGameExeFinder.java:106)
	at de.peeeq.wurstio.utils.W3Utils.parsePatchVersion(W3Utils.java:50)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.parseCustomPatchVersion(MapRequest.java:374)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.compileScript(MapRequest.java:358)
	at de.peeeq.wurstio.languageserver.requests.BuildMap.execute(BuildMap.java:62)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:171)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:29)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:146)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Exception: tried: [Warcraft III.exe, Frozen Throne.exe, war3.exe, x86\Warcraft III.exe, x86_64\Warcraft III.exe]
	... 11 more
net.moonlightflower.wc3libs.port.NotFoundException
	at net.moonlightflower.wc3libs.port.win.WinGameExeFinder.find(WinGameExeFinder.java:141)
	at net.moonlightflower.wc3libs.port.win.WinGameExeFinder.find(WinGameExeFinder.java:12)
	at net.moonlightflower.wc3libs.port.Finder.get(Finder.java:25)
	at net.moonlightflower.wc3libs.port.StdGameExeFinder.find(StdGameExeFinder.java:39)
	at net.moonlightflower.wc3libs.port.StdGameExeFinder.find(StdGameExeFinder.java:12)
	at net.moonlightflower.wc3libs.port.Finder.get(Finder.java:25)
	at de.peeeq.wurstio.utils.W3Utils.getWc3PatchVersion(W3Utils.java:26)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.parseCustomPatchVersion(MapRequest.java:375)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.compileScript(MapRequest.java:358)
	at de.peeeq.wurstio.languageserver.requests.BuildMap.execute(BuildMap.java:62)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:171)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:29)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:146)
	at java.lang.Thread.run(Unknown Source)
```

I tried uninstalling, deleting all related files in Program Files and reinstalling the game with no luck.

**Comment by Frotty** [comment]
Can't find your game executable, set it in config or provide more info.

**Comment by Cokemonkey11** [comment]
@Frotty I spoke to William about this. The game binaries have been moved into x64 and x86 directories, so we should discover both

And the launch option is `-launch -loadfile <path to map>`

**Comment by Frotty** [comment]
They have been moved long ago, and it is handled as you can see from the log which tries following binary locations `tried: [Warcraft III.exe, Frozen Throne.exe, war3.exe, x86\Warcraft III.exe, x86_64\Warcraft III.exe]`.
If these folders changed again, you need to provide the specific details.

**Comment by LunarTech8** [comment]
For people stumbling on the same problem after not updating for a time:
The exe might have been moved from "..\\Warcraft III" or "...\\Warcraft III\\x86_64" to "...\\Warcraft III\\**\_retail\_**\\x86_64".
Thus the "wurst.wc3path" field in .vscode\\settings.json has to be adjusted accordingly.

**Comment by Cokemonkey11** [comment]
I think a number of us didn't have this `_retail_` until 1.32
